--- 
title: "MSKCC Biostatistics Course"
date: "Last Updated: `r format(Sys.Date(), format='%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
rmd_files: ["index.Rmd", "01-week1.Rmd", "02-week2.Rmd", "03-week3.Rmd", "04-week4.Rmd", "05-week5.Rmd", "06-week6.Rmd", "07-week7.Rmd", "08-week8.Rmd", "09-answers.Rmd"]
bibliography: [packages.bib]
biblio-style: apalike
link-citations: yes
description: "Statistics Course"
---

# General Course Materials {-}

## Course Outline {-}

## Andrew's Contact Details {-}

If you are stuck, feel free to get in contact seven days a week, 7am – 10pm. 

Call me at home 718 832 1320 or on my cell phone 347 244 6934 

If it is non-urgent, email me on vickersa@mskcc.org

Some typical problems and what to do about them:

1. _I can't access R / RStudio / the website isn't working._ Contact the help desk!
2. _I want to do a regression but can't work out the right R command._ Contact me by phone.
3. _I don't know whether to do a regression or a correlation._ Pick one or the other and raise this as a question in class.
4. _I don't understand the R output._ Call me if you are totally in the dark; otherwise do your best and raise this as a question in class.
5. _I was going to do the assignment, but my dog got ill and I had laptop problems and can I do the assignment for Tuesday instead?_ Yawn.
6. _I don't understand the question._ Call me.
7. _I am not sure I understand the difference between a regression and a correlation._ Raise this in class.

## Passing the Course {-}

You can only get "credit" for this course if you pass. I am occasionally asked to write a letter for a former student stating that they "took part in the MSKCC biostatistics course". Now because I don't take register or have a sign-up sheet, I can't possibly know who took part and who didn't. So I only write letters saying that a former student passed.

To pass, you have to meet three conditions:

1. Be officially signed up
2. Pass the exam
3. Answer the feedback

**About the exam**

The exam is given at the end of the course. It is posted on the course website and is an "open book" exam: you do this in your own time and send me your answers. Some notes and thoughts about the exam:

1. There are only a few questions. It shouldn't take longer than a couple of hours to do and I give you two weeks to complete it.
2. The questions I give are far easier than the typical statistical problems you are likely to encounter in the course of a research career. 
3. I mark very liberally, and have a low pass mark (50%).
4. Anyone who fails the exam is given an opportunity to resubmit.

**Feedback**

Cheryl James or one of her colleagues will send you an email shortly asking for your feedback on the course. Although this is forwarded to me anonymously, Cheryl’s office will take a note of who responded and who didn’t. If you don’t complete your feedback back form, you won’t pass the course.

**Working groups**

I am perfectly happy for you to work in small groups as long as:

1. You are clear and explicit about this up front
2. All members of a group contribute equally
3. You don’t take advantage

Note that we have had problems with plagiarism before. It is absolutely straightforward for me to detect this using simple software. 

## Data Checking Procedures {-}

## Guidelines for presentation of statistics {-}

Please review these guidelines on the course website.

<!--chapter:end:index.Rmd-->


# Week 1

Placeholder


## R Instructions
### Using RStudio
### Setting Up RStudio
### Opening a data file created by someone else
## Looking at the data
### Typing a command
### Some Useful Commands
#### Extracting a variable by name ($)
#### Pipe operator (%>%)
#### `head` function
#### `str` function
#### `tbl_summary` function
#### `skim` function
#### `mutate` function
#### `if_else` function
### Using Help
## Assignments

<!--chapter:end:01-week1.Rmd-->


# Week 2

Placeholder


## R Instructions
### Summarizing continuous variables
### Centiles
### One-way tables
### Two-way tables
### Graphing
### Further Reading
### Using R as a calculator
## Assignment
### Assignments

<!--chapter:end:02-week2.Rmd-->


# Week 3

Placeholder


## R Instructions
## Assignments

<!--chapter:end:03-week3.Rmd-->


# Week 4

Placeholder


## R Instructions
## Assignments

<!--chapter:end:04-week4.Rmd-->


# Week 5

Placeholder


## R Instructions
### Correlation
### Linear regression
### Graphing the data
### Logistic regression
### Getting the area-under-the-curve
## Assignments

<!--chapter:end:05-week5.Rmd-->


# Week 6

Placeholder


## R Instructions
### Diagnostic Tests
## Assignments

<!--chapter:end:06-week6.Rmd-->


# Week 7

Placeholder


## R Instructions
### Time to event data
## Assignments

<!--chapter:end:07-week7.Rmd-->

# Week 8

Statistical Slipups Powerpoint Presentation

[[TODO: Add link after pushed to Github]]

<!--chapter:end:08-week8.Rmd-->


# Assignment Answers

Placeholder


## Week 1
## Week 2
### lesson2a.rds: Marathon Runners
### lesson2b.rds: Postoperative Pain
### lesson2c.rds: Radical Prostatectomy Cohort
### lesson2d.rds: Cost of a Minor Medical Procedure
### lesson2e.rds: Cancer pain
## Week 3
### lesson3a.rds
### lesson3b.rds
### lesson3c.rds
### lesson3d.rds
### lesson3e.rds
### lesson3f.rds
## Week 4
### lesson4a.rds
### lesson4b.rds
### lesson4c.rds
### lesson4d.rds
### lesson4e.rds
## Week 5
### lesson5a.rds
### lesson5b.rds
### lesson5c.rds
### lesson5d.rds
### lesson5e.rds
### lesson5f.rds
### lesson5g.rds
### lesson5h.rds
### lesson5i.rds
## Week 6
### lesson6a.rds and lesson6b.rds
### lesson6c.rds
### lesson6d.rds
### lesson6e
### lesson6f
### lesson6g
## Week 7
### lesson7a
### lesson7b.rds
### lesson7c.rds
### lesson7d.rds

<!--chapter:end:09-answers.Rmd-->


# Exam

Placeholder


## Question 1
## Question 2
## Question 3
## Question 4

<!--chapter:end:10-exam.Rmd-->

