<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Week 3 | MSKCC Biostatistics Course</title>
  <meta name="description" content="Statistics Course" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Week 3 | MSKCC Biostatistics Course" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Statistics Course" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Week 3 | MSKCC Biostatistics Course" />
  
  <meta name="twitter:description" content="Statistics Course" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-2.html"/>
<link rel="next" href="week-4.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>General Course Materials</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-outline"><i class="fa fa-check"></i>Course Outline</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#andrews-contact-details"><i class="fa fa-check"></i>Andrew’s Contact Details</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#passing-the-course"><i class="fa fa-check"></i>Passing the Course</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#data-checking-procedures"><i class="fa fa-check"></i>Data Checking Procedures</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#guidelines-for-presentation-of-statistics"><i class="fa fa-check"></i>Guidelines for presentation of statistics</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1.html"><a href="week-1.html"><i class="fa fa-check"></i><b>1</b> Week 1</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1.html"><a href="week-1.html#setting-up"><i class="fa fa-check"></i><b>1.1</b> Setting Up</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="week-1.html"><a href="week-1.html#software-installation"><i class="fa fa-check"></i><b>1.1.1</b> Software Installation</a></li>
<li class="chapter" data-level="1.1.2" data-path="week-1.html"><a href="week-1.html#setting-up-course-files"><i class="fa fa-check"></i><b>1.1.2</b> Setting up course files</a></li>
<li class="chapter" data-level="1.1.3" data-path="week-1.html"><a href="week-1.html#using-rstudio"><i class="fa fa-check"></i><b>1.1.3</b> Using RStudio</a></li>
<li class="chapter" data-level="1.1.4" data-path="week-1.html"><a href="week-1.html#installing-packages"><i class="fa fa-check"></i><b>1.1.4</b> Installing packages</a></li>
<li class="chapter" data-level="1.1.5" data-path="week-1.html"><a href="week-1.html#a-note-about-packages"><i class="fa fa-check"></i><b>1.1.5</b> A Note About Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="week-1.html"><a href="week-1.html#r-instructions"><i class="fa fa-check"></i><b>1.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="week-1.html"><a href="week-1.html#opening-a-data-file-created-by-someone-else"><i class="fa fa-check"></i><b>1.2.1</b> Opening a data file created by someone else</a></li>
<li class="chapter" data-level="1.2.2" data-path="week-1.html"><a href="week-1.html#loading-packages"><i class="fa fa-check"></i><b>1.2.2</b> Loading packages</a></li>
<li class="chapter" data-level="1.2.3" data-path="week-1.html"><a href="week-1.html#looking-at-the-data"><i class="fa fa-check"></i><b>1.2.3</b> Looking at the data</a></li>
<li class="chapter" data-level="1.2.4" data-path="week-1.html"><a href="week-1.html#typing-a-command"><i class="fa fa-check"></i><b>1.2.4</b> Typing a command</a></li>
<li class="chapter" data-level="1.2.5" data-path="week-1.html"><a href="week-1.html#some-useful-commands"><i class="fa fa-check"></i><b>1.2.5</b> Some Useful Commands</a></li>
<li class="chapter" data-level="1.2.6" data-path="week-1.html"><a href="week-1.html#using-help"><i class="fa fa-check"></i><b>1.2.6</b> Using Help</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="week-1.html"><a href="week-1.html#assignments"><i class="fa fa-check"></i><b>1.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>2</b> Week 2</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-2.html"><a href="week-2.html#setting-up-1"><i class="fa fa-check"></i><b>2.1</b> Setting Up</a></li>
<li class="chapter" data-level="2.2" data-path="week-2.html"><a href="week-2.html#r-instructions-1"><i class="fa fa-check"></i><b>2.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="week-2.html"><a href="week-2.html#looking-at-your-data"><i class="fa fa-check"></i><b>2.2.1</b> Looking at your data</a></li>
<li class="chapter" data-level="2.2.2" data-path="week-2.html"><a href="week-2.html#summarizing-continuous-variables"><i class="fa fa-check"></i><b>2.2.2</b> Summarizing continuous variables</a></li>
<li class="chapter" data-level="2.2.3" data-path="week-2.html"><a href="week-2.html#centiles"><i class="fa fa-check"></i><b>2.2.3</b> Centiles</a></li>
<li class="chapter" data-level="2.2.4" data-path="week-2.html"><a href="week-2.html#one-way-tables"><i class="fa fa-check"></i><b>2.2.4</b> One-way tables</a></li>
<li class="chapter" data-level="2.2.5" data-path="week-2.html"><a href="week-2.html#two-way-tables"><i class="fa fa-check"></i><b>2.2.5</b> Two-way tables</a></li>
<li class="chapter" data-level="2.2.6" data-path="week-2.html"><a href="week-2.html#subsetting-data"><i class="fa fa-check"></i><b>2.2.6</b> Subsetting Data</a></li>
<li class="chapter" data-level="2.2.7" data-path="week-2.html"><a href="week-2.html#graphing"><i class="fa fa-check"></i><b>2.2.7</b> Graphing</a></li>
<li class="chapter" data-level="2.2.8" data-path="week-2.html"><a href="week-2.html#further-reading"><i class="fa fa-check"></i><b>2.2.8</b> Further Reading</a></li>
<li class="chapter" data-level="2.2.9" data-path="week-2.html"><a href="week-2.html#using-r-as-a-calculator"><i class="fa fa-check"></i><b>2.2.9</b> Using R as a calculator</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="week-2.html"><a href="week-2.html#assignments-1"><i class="fa fa-check"></i><b>2.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i><b>3</b> Week 3</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-3.html"><a href="week-3.html#setting-up-2"><i class="fa fa-check"></i><b>3.1</b> Setting up</a></li>
<li class="chapter" data-level="3.2" data-path="week-3.html"><a href="week-3.html#r-instructions-2"><i class="fa fa-check"></i><b>3.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="week-3.html"><a href="week-3.html#example-datasets"><i class="fa fa-check"></i><b>3.2.1</b> Example Datasets</a></li>
<li class="chapter" data-level="3.2.2" data-path="week-3.html"><a href="week-3.html#hypothesis-testing"><i class="fa fa-check"></i><b>3.2.2</b> Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="week-3.html"><a href="week-3.html#assignments-2"><i class="fa fa-check"></i><b>3.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>4</b> Week 4</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-4.html"><a href="week-4.html#setting-up-3"><i class="fa fa-check"></i><b>4.1</b> Setting Up</a></li>
<li class="chapter" data-level="4.2" data-path="week-4.html"><a href="week-4.html#r-instructions-3"><i class="fa fa-check"></i><b>4.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="week-4.html"><a href="week-4.html#tables-1"><i class="fa fa-check"></i><b>4.2.1</b> Tables</a></li>
<li class="chapter" data-level="4.2.2" data-path="week-4.html"><a href="week-4.html#getting-estimates-risk-difference-risk-ratio-odds-ratio"><i class="fa fa-check"></i><b>4.2.2</b> Getting estimates: risk difference, risk ratio, odds ratio</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="week-4.html"><a href="week-4.html#assignments-3"><i class="fa fa-check"></i><b>4.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>5</b> Week 5</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-5.html"><a href="week-5.html#setting-up-4"><i class="fa fa-check"></i><b>5.1</b> Setting Up</a></li>
<li class="chapter" data-level="5.2" data-path="week-5.html"><a href="week-5.html#r-instructions-4"><i class="fa fa-check"></i><b>5.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="week-5.html"><a href="week-5.html#correlation"><i class="fa fa-check"></i><b>5.2.1</b> Correlation</a></li>
<li class="chapter" data-level="5.2.2" data-path="week-5.html"><a href="week-5.html#linear-regression"><i class="fa fa-check"></i><b>5.2.2</b> Linear regression</a></li>
<li class="chapter" data-level="5.2.3" data-path="week-5.html"><a href="week-5.html#graphing-the-data"><i class="fa fa-check"></i><b>5.2.3</b> Graphing the data</a></li>
<li class="chapter" data-level="5.2.4" data-path="week-5.html"><a href="week-5.html#logistic-regression"><i class="fa fa-check"></i><b>5.2.4</b> Logistic regression</a></li>
<li class="chapter" data-level="5.2.5" data-path="week-5.html"><a href="week-5.html#getting-the-area-under-the-curve"><i class="fa fa-check"></i><b>5.2.5</b> Getting the area-under-the-curve</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="week-5.html"><a href="week-5.html#assignments-4"><i class="fa fa-check"></i><b>5.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>6</b> Week 6</a>
<ul>
<li class="chapter" data-level="6.1" data-path="week-6.html"><a href="week-6.html#setting-up-5"><i class="fa fa-check"></i><b>6.1</b> Setting Up</a></li>
<li class="chapter" data-level="6.2" data-path="week-6.html"><a href="week-6.html#r-instructions-5"><i class="fa fa-check"></i><b>6.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="week-6.html"><a href="week-6.html#diagnostic-tests"><i class="fa fa-check"></i><b>6.2.1</b> Diagnostic Tests</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="week-6.html"><a href="week-6.html#assignments-5"><i class="fa fa-check"></i><b>6.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>7</b> Week 7</a>
<ul>
<li class="chapter" data-level="7.1" data-path="week-7.html"><a href="week-7.html#setting-up-6"><i class="fa fa-check"></i><b>7.1</b> Setting Up</a></li>
<li class="chapter" data-level="7.2" data-path="week-7.html"><a href="week-7.html#r-instructions-6"><i class="fa fa-check"></i><b>7.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="week-7.html"><a href="week-7.html#introductory-remarks-on-time-to-event-analysis"><i class="fa fa-check"></i><b>7.2.1</b> Introductory remarks on time-to-event analysis</a></li>
<li class="chapter" data-level="7.2.2" data-path="week-7.html"><a href="week-7.html#time-to-event-data"><i class="fa fa-check"></i><b>7.2.2</b> Time to event data</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="week-7.html"><a href="week-7.html#assignments-6"><i class="fa fa-check"></i><b>7.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8.html"><a href="week-8.html"><i class="fa fa-check"></i><b>8</b> Week 8</a></li>
<li class="chapter" data-level="9" data-path="assignment-answers.html"><a href="assignment-answers.html"><i class="fa fa-check"></i><b>9</b> Assignment Answers</a>
<ul>
<li class="chapter" data-level="9.1" data-path="assignment-answers.html"><a href="assignment-answers.html#week-1-1"><i class="fa fa-check"></i><b>9.1</b> Week 1</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson1a.rds"><i class="fa fa-check"></i><b>9.1.1</b> lesson1a.rds</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="assignment-answers.html"><a href="assignment-answers.html#week-2-1"><i class="fa fa-check"></i><b>9.2</b> Week 2</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2a.rds"><i class="fa fa-check"></i><b>9.2.1</b> lesson2a.rds</a></li>
<li class="chapter" data-level="9.2.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2b.rds"><i class="fa fa-check"></i><b>9.2.2</b> lesson2b.rds</a></li>
<li class="chapter" data-level="9.2.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2c.rds"><i class="fa fa-check"></i><b>9.2.3</b> lesson2c.rds</a></li>
<li class="chapter" data-level="9.2.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2d.rds"><i class="fa fa-check"></i><b>9.2.4</b> lesson2d.rds</a></li>
<li class="chapter" data-level="9.2.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2e.rds"><i class="fa fa-check"></i><b>9.2.5</b> lesson2e.rds</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="assignment-answers.html"><a href="assignment-answers.html#week-3-1"><i class="fa fa-check"></i><b>9.3</b> Week 3</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3a.rds"><i class="fa fa-check"></i><b>9.3.1</b> lesson3a.rds</a></li>
<li class="chapter" data-level="9.3.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3b.rds"><i class="fa fa-check"></i><b>9.3.2</b> lesson3b.rds</a></li>
<li class="chapter" data-level="9.3.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3c.rds"><i class="fa fa-check"></i><b>9.3.3</b> lesson3c.rds</a></li>
<li class="chapter" data-level="9.3.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3d.rds"><i class="fa fa-check"></i><b>9.3.4</b> lesson3d.rds</a></li>
<li class="chapter" data-level="9.3.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3e.rds"><i class="fa fa-check"></i><b>9.3.5</b> lesson3e.rds</a></li>
<li class="chapter" data-level="9.3.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3f.rds"><i class="fa fa-check"></i><b>9.3.6</b> lesson3f.rds</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="assignment-answers.html"><a href="assignment-answers.html#week-4-1"><i class="fa fa-check"></i><b>9.4</b> Week 4</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4a.rds"><i class="fa fa-check"></i><b>9.4.1</b> lesson4a.rds</a></li>
<li class="chapter" data-level="9.4.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4b.rds"><i class="fa fa-check"></i><b>9.4.2</b> lesson4b.rds</a></li>
<li class="chapter" data-level="9.4.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4c.rds"><i class="fa fa-check"></i><b>9.4.3</b> lesson4c.rds</a></li>
<li class="chapter" data-level="9.4.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4d.rds"><i class="fa fa-check"></i><b>9.4.4</b> lesson4d.rds</a></li>
<li class="chapter" data-level="9.4.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4e.rds"><i class="fa fa-check"></i><b>9.4.5</b> lesson4e.rds</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="assignment-answers.html"><a href="assignment-answers.html#week-5-1"><i class="fa fa-check"></i><b>9.5</b> Week 5</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5a.rds"><i class="fa fa-check"></i><b>9.5.1</b> lesson5a.rds</a></li>
<li class="chapter" data-level="9.5.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5b.rds"><i class="fa fa-check"></i><b>9.5.2</b> lesson5b.rds</a></li>
<li class="chapter" data-level="9.5.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5c.rds"><i class="fa fa-check"></i><b>9.5.3</b> lesson5c.rds</a></li>
<li class="chapter" data-level="9.5.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5d.rds"><i class="fa fa-check"></i><b>9.5.4</b> lesson5d.rds</a></li>
<li class="chapter" data-level="9.5.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5e.rds"><i class="fa fa-check"></i><b>9.5.5</b> lesson5e.rds</a></li>
<li class="chapter" data-level="9.5.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5f.rds"><i class="fa fa-check"></i><b>9.5.6</b> lesson5f.rds</a></li>
<li class="chapter" data-level="9.5.7" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5g.rds"><i class="fa fa-check"></i><b>9.5.7</b> lesson5g.rds</a></li>
<li class="chapter" data-level="9.5.8" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5h.rds"><i class="fa fa-check"></i><b>9.5.8</b> lesson5h.rds</a></li>
<li class="chapter" data-level="9.5.9" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5i.rds"><i class="fa fa-check"></i><b>9.5.9</b> lesson5i.rds</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="assignment-answers.html"><a href="assignment-answers.html#week-6-1"><i class="fa fa-check"></i><b>9.6</b> Week 6</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6a.rds-and-lesson6b.rds"><i class="fa fa-check"></i><b>9.6.1</b> lesson6a.rds and lesson6b.rds</a></li>
<li class="chapter" data-level="9.6.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6c.rds"><i class="fa fa-check"></i><b>9.6.2</b> lesson6c.rds</a></li>
<li class="chapter" data-level="9.6.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6d.rds"><i class="fa fa-check"></i><b>9.6.3</b> lesson6d.rds</a></li>
<li class="chapter" data-level="9.6.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6e"><i class="fa fa-check"></i><b>9.6.4</b> lesson6e</a></li>
<li class="chapter" data-level="9.6.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6f"><i class="fa fa-check"></i><b>9.6.5</b> lesson6f</a></li>
<li class="chapter" data-level="9.6.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6g"><i class="fa fa-check"></i><b>9.6.6</b> lesson6g</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="assignment-answers.html"><a href="assignment-answers.html#week-7-1"><i class="fa fa-check"></i><b>9.7</b> Week 7</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7a.rds"><i class="fa fa-check"></i><b>9.7.1</b> lesson7a.rds</a></li>
<li class="chapter" data-level="9.7.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7b.rds"><i class="fa fa-check"></i><b>9.7.2</b> lesson7b.rds</a></li>
<li class="chapter" data-level="9.7.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7c.rds"><i class="fa fa-check"></i><b>9.7.3</b> lesson7c.rds</a></li>
<li class="chapter" data-level="9.7.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7d.rds"><i class="fa fa-check"></i><b>9.7.4</b> lesson7d.rds</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MSKCC Biostatistics Course</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-3" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Week 3</h1>
<div id="setting-up-2" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Setting up</h2>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="week-3.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb99-2"><a href="week-3.html#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb99-3"><a href="week-3.html#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb99-4"><a href="week-3.html#cb99-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb99-5"><a href="week-3.html#cb99-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epiR)</span>
<span id="cb99-6"><a href="week-3.html#cb99-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb99-7"><a href="week-3.html#cb99-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb99-8"><a href="week-3.html#cb99-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span>
<span id="cb99-9"><a href="week-3.html#cb99-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb99-10"><a href="week-3.html#cb99-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb99-11"><a href="week-3.html#cb99-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb99-12"><a href="week-3.html#cb99-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-13"><a href="week-3.html#cb99-13" aria-hidden="true" tabindex="-1"></a><span class="co"># The &quot;trial&quot; and &quot;midwest&quot; datasets are available automatically </span></span>
<span id="cb99-14"><a href="week-3.html#cb99-14" aria-hidden="true" tabindex="-1"></a><span class="co"># after you load the packages above</span></span>
<span id="cb99-15"><a href="week-3.html#cb99-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-16"><a href="week-3.html#cb99-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Load other data necessary to run Week 3 examples</span></span>
<span id="cb99-17"><a href="week-3.html#cb99-17" aria-hidden="true" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 1&quot;</span>, <span class="st">&quot;lesson1a.rds&quot;</span>))</span>
<span id="cb99-18"><a href="week-3.html#cb99-18" aria-hidden="true" tabindex="-1"></a>example3a <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 3&quot;</span>, <span class="st">&quot;example3a.rds&quot;</span>))</span></code></pre></div>
</div>
<div id="r-instructions-2" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> R Instructions</h2>
<div id="example-datasets" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Example Datasets</h3>
<p>Normally, to do an analysis in R, you will have to load in a dataset. However, R and some packages come with built-in example datasets. For example, there is a dataset called “trial” that comes built in with the <code>gtsummary</code> package. We will use the “trial” dataset for many examples, but you do not need to load it, as the “trial” dataset will automatically be loaded after you run <code>library(gtsummary)</code>.</p>
</div>
<div id="hypothesis-testing" class="section level3" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Hypothesis Testing</h3>
<p>For this week’s assignment, you will need to learn the following functions:</p>
<ul>
<li><code>t.test</code></li>
<li><code>wilcox.test</code></li>
<li><code>binom.test</code></li>
</ul>
<div id="t-test" class="section level4" number="3.2.2.1">
<h4><span class="header-section-number">3.2.2.1</span> <strong>t-test</strong></h4>
<p>This is used to compare a continuous outcome (such as hemoglobin) in two groups (e.g. vegetarians and carnivores, or patients in a randomized trial receiving an anemia treatment or placebo). Now statisticians normally say that the t-test makes two assumptions: (1) data are normally distributed and (2) variances are equal. Don’t worry about assumption (2) for now. Also, assumption (1) has an odd feature: it doesn’t matter once sample sizes get large (for those of you who want to boast that you know a “theorem,” this is called the “central limit theorem”). Just how large is “large” is a matter of judgment, but generally speaking, it is said that you can feel okay using a t-test on non-normal data once the sample size is above 30 a group. As it turns out, the t-test is “robust” to non-normal data, even if sample sizes are low. “Robust” means that it gives similar results regardless of whether the data are normally distributed or not. So many people feel comfortable using the t-test for to compare a continuous outcome between two groups even if the data are pretty skewed.</p>
<p><strong>Different forms of the t-test</strong></p>
<p>The two main forms of the t-test are “paired” and “unpaired.”</p>
<p>“Unpaired” is used when, for example, testing marker levels between two groups taking different drugs, as there are different patients in each group:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="week-3.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-test for marker levels between treatment arms</span></span>
<span id="cb100-2"><a href="week-3.html#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(marker <span class="sc">~</span> trt, <span class="at">data =</span> trial, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  marker by trt
## t = 1.5816, df = 188, p-value = 0.1154
## alternative hypothesis: true difference in means between group Drug A and group Drug B is not equal to 0
## 95 percent confidence interval:
##  -0.04858916  0.44161134
## sample estimates:
## mean in group Drug A mean in group Drug B 
##            1.0173478            0.8208367</code></pre>
<p>The first variable, “marker,” is the continuous endpoint that you are comparing by the two groups of the second variable, “trt” (Drug A vs Drug B). Next, you are telling R to get the data from the dataset called “trial.” <code>paired = FALSE</code> indicates that you want to perform an “unpaired” test. The last option (<code>var.equal = TRUE</code>) tells the <code>t.test</code> function to treat the two variances as being equal. For this course, you will need to include this option in two-group <code>t.test</code> commands but you do not need to know specific details about this concept.</p>
<p>A “paired” test would be used for comparing blood pressure taken before and after an intervention, for example, because you are looking at two observations on the same patient.</p>
<!-- Note: Don't need to specify "var.equal = TRUE" for paired tests, as this is the default, but I thought it might be easier to be consistent across all. -->
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="week-3.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># paired t-test for blood pressure between &quot;before&quot; and &quot;after&quot; groups</span></span>
<span id="cb102-2"><a href="week-3.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bp <span class="sc">~</span> when, <span class="at">data =</span> example3a, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  bp by when
## t = -3.3372, df = 119, p-value = 0.00113
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -8.112776 -2.070557
## sample estimates:
## mean of the differences 
##               -5.091667</code></pre>
<p>Here, the code is the same as the last example, with “bp” as the continuous outcome, and “when” indicating the two groups. Since these are two measurements taken on the same patient, a paired t-test is necessary, so the option <code>paired = TRUE</code> must be included.</p>
<p>A single sample test compares the mean of a group of observations with some hypothetical value, for example, is the average rate of college-educated adults in the midwest different than the national average of 32%?</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="week-3.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-test assessing whether the rate of college education is different than 32%</span></span>
<span id="cb104-2"><a href="week-3.html#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(midwest<span class="sc">$</span>percollege, <span class="at">mu =</span> <span class="dv">32</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  midwest$percollege
## t = -45.827, df = 436, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 32
## 95 percent confidence interval:
##  17.68400 18.86147
## sample estimates:
## mean of x 
##  18.27274</code></pre>
<p>Let’s look at the print out from a t-test in more detail:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="week-3.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-test for difference in horsepower for manual vs automatic transmission</span></span>
<span id="cb106-2"><a href="week-3.html#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(hp <span class="sc">~</span> am, <span class="at">data =</span> mtcars, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  hp by am
## t = 1.3733, df = 30, p-value = 0.1798
## alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
## 95 percent confidence interval:
##  -16.27768  83.11169
## sample estimates:
## mean in group 0 mean in group 1 
##        160.2632        126.8462</code></pre>
<p>This example is testing whether there is a difference in horsepower (hp) between cars with an automatic transmission (am == 0) vs manual transmission (am == 1).</p>
<p>The <code>t.test</code> function reports the data and variables you are testing, followed by the t statistic (t), degrees of freedom (df) and p-value. Below that, it states the alternative hypothesis you are testing, prints the mean in each group, and gives the 95% confidence interval around the difference in group means.</p>
<p>While for an unpaired test, the <code>t.test</code> command prints the group means in each group, you may want to report the difference between means. The group means are stored in the <code>t.test</code> results under <code>estimate</code>.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="week-3.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform t-test and save out results as &quot;hp_test&quot;</span></span>
<span id="cb108-2"><a href="week-3.html#cb108-2" aria-hidden="true" tabindex="-1"></a>hp_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(hp <span class="sc">~</span> am, <span class="at">data =</span> mtcars, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb108-3"><a href="week-3.html#cb108-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-4"><a href="week-3.html#cb108-4" aria-hidden="true" tabindex="-1"></a><span class="co"># show the group means from &quot;hp_test&quot;</span></span>
<span id="cb108-5"><a href="week-3.html#cb108-5" aria-hidden="true" tabindex="-1"></a>hp_test<span class="sc">$</span>estimate</span></code></pre></div>
<pre><code>## mean in group 0 mean in group 1 
##        160.2632        126.8462</code></pre>
<p>To calculate the difference in means between group 0 and group 1, you can use the <code>estimate</code> data to calculate this. The square brackets indicate which number (first mean or second mean) to take. This works to calculate the difference between group 0 and group 1, as well as between group 1 and group 0.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="week-3.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can save out the means for each group</span></span>
<span id="cb110-2"><a href="week-3.html#cb110-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-3"><a href="week-3.html#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The first value is mean in group 0</span></span>
<span id="cb110-4"><a href="week-3.html#cb110-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (&quot;mean in group 0&quot; is printed first in results)</span></span>
<span id="cb110-5"><a href="week-3.html#cb110-5" aria-hidden="true" tabindex="-1"></a>mean_group0 <span class="ot">&lt;-</span> hp_test<span class="sc">$</span>estimate[[<span class="dv">1</span>]]</span>
<span id="cb110-6"><a href="week-3.html#cb110-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-7"><a href="week-3.html#cb110-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The second value is mean in group 1</span></span>
<span id="cb110-8"><a href="week-3.html#cb110-8" aria-hidden="true" tabindex="-1"></a>mean_group1 <span class="ot">&lt;-</span> hp_test<span class="sc">$</span>estimate[[<span class="dv">2</span>]]</span>
<span id="cb110-9"><a href="week-3.html#cb110-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-10"><a href="week-3.html#cb110-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Subtract the mean in group 1 from the mean in group 0</span></span>
<span id="cb110-11"><a href="week-3.html#cb110-11" aria-hidden="true" tabindex="-1"></a>mean_group0 <span class="sc">-</span> mean_group1</span></code></pre></div>
<pre><code>## [1] 33.417</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="week-3.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subtract the mean in group 0 from the mean in group 1</span></span>
<span id="cb112-2"><a href="week-3.html#cb112-2" aria-hidden="true" tabindex="-1"></a>mean_group1 <span class="sc">-</span> mean_group0</span></code></pre></div>
<pre><code>## [1] -33.417</code></pre>
<p>You don’t need to worry about the t statistic or degrees of freedom (df). The numbers you are most interested in are the p-value, the group means, and the 95% confidence interval.</p>
<p>Now we haven’t discussed the 95% confidence interval yet, but think of it in simple terms as a plausible range of true values of the difference between means. In this data, the average horsepower is 33.4 higher in cars with an automatic transmission, but it could be that, in fact, the true horsepower is between 16.3 lower or 83.1 higher in the automatic group vs the manual group.</p>
</div>
<div id="non-parametric-methods" class="section level4" number="3.2.2.2">
<h4><span class="header-section-number">3.2.2.2</span> <strong>Non-parametric methods</strong></h4>
<p>These are used to compare continuous outcomes in two groups. There are no assumptions about normality or variance.</p>
<p>Unpaired case, for example, do marker levels differ between the drug and placebo groups?</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="week-3.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># non-parametric test for difference in marker levels by treatment group</span></span>
<span id="cb114-2"><a href="week-3.html#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(marker <span class="sc">~</span> trt, <span class="at">data =</span> trial, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  marker by trt
## W = 5161.5, p-value = 0.08475
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>The inputs for the <code>wilcox.test</code> function are very similar to the inputs for the <code>t.test</code> function. You will see here we are using the same example - comparing marker levels by treatment group, so the outcome variable (“marker”), the group variable (“trt”) and the dataset (“trial”) are all the same. This is still an unpaired test (<code>paired = FALSE</code>).</p>
<p>Paired case, for example, does an intervention cause a change in a patient’s blood pressure?</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="week-3.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># paired non-parametric test for difference in &quot;before&quot; and &quot;after&quot; blood pressure measurements</span></span>
<span id="cb116-2"><a href="week-3.html#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(bp <span class="sc">~</span> when, <span class="at">data =</span> example3a, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  bp by when
## W = 5551, p-value = 0.002166
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Single sample, for example, is the rate of college education in the midwest different than the national average (32%)?</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="week-3.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co"># non-parametric test - is rate of college education different from 32%?</span></span>
<span id="cb118-2"><a href="week-3.html#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(midwest<span class="sc">$</span>percollege, <span class="at">mu =</span> <span class="dv">32</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  midwest$percollege
## V = 924, p-value &lt; 2.2e-16
## alternative hypothesis: true location is not equal to 32</code></pre>
<p>Note here that you don’t get any parameters for the groups such as means, medians or standard deviations. You also don’t get an estimate for the difference between groups.</p>
</div>
<div id="the-binomial-test" class="section level4" number="3.2.2.3">
<h4><span class="header-section-number">3.2.2.3</span> <strong>The binomial test</strong></h4>
<p>The binomial test compares a proportion to a hypothesized value. For example, what is the probability that an unbiased coin thrown 100 times would give a result as or more extreme than 60 heads? (This probability is equivalent to the p-value).</p>
<p>The first argument of <code>binom.test</code> is the number of successes, then the number of total tests (total observations). The hypothesized probability is specified by the <code>p =</code> option - the default is 0.5 (50%).</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="week-3.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare a proportion to a hypothesized value &quot;p&quot;</span></span>
<span id="cb120-2"><a href="week-3.html#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">60</span>, <span class="dv">100</span>, <span class="at">p =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  60 and 100
## number of successes = 60, number of trials = 100, p-value = 0.05689
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.4972092 0.6967052
## sample estimates:
## probability of success 
##                    0.6</code></pre>
<p>You can also use <code>binom.test</code> on data from a dataset. For example, if we want to test whether the proportion of women (sex = 1) is different from 50%:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="week-3.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The &quot;sum&quot; function adds up the number of observations where sex == 1 (women)</span></span>
<span id="cb122-2"><a href="week-3.html#cb122-2" aria-hidden="true" tabindex="-1"></a>nwomen <span class="ot">&lt;-</span> <span class="fu">sum</span>(lesson1a<span class="sc">$</span>sex)</span>
<span id="cb122-3"><a href="week-3.html#cb122-3" aria-hidden="true" tabindex="-1"></a>nwomen</span></code></pre></div>
<pre><code>## [1] 205</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="week-3.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The &quot;nrow&quot; function (for &quot;number of rows&quot;) counts the total number of observations</span></span>
<span id="cb124-2"><a href="week-3.html#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The &quot;filter&quot; function is used to count only the number of observations where</span></span>
<span id="cb124-3"><a href="week-3.html#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="co"># &quot;sex&quot; is not missing (NA)</span></span>
<span id="cb124-4"><a href="week-3.html#cb124-4" aria-hidden="true" tabindex="-1"></a>ntotal <span class="ot">&lt;-</span> <span class="fu">nrow</span>(lesson1a <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(sex)))</span>
<span id="cb124-5"><a href="week-3.html#cb124-5" aria-hidden="true" tabindex="-1"></a>ntotal</span></code></pre></div>
<pre><code>## [1] 386</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="week-3.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare a proportion of patients in a dataset to a hypothesized value &quot;p&quot;</span></span>
<span id="cb126-2"><a href="week-3.html#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(nwomen, ntotal, <span class="at">p =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  nwomen and ntotal
## number of successes = 205, number of trials = 386, p-value = 0.2417
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.4799345 0.5817614
## sample estimates:
## probability of success 
##              0.5310881</code></pre>
<p>Note that above, we used the <code>filter</code> function to only count those observations where “sex” was not missing (NA). The function <code>is.na</code> gives a value of TRUE if the data is missing (NA) and FALSE if the data is non-missing. The <code>!</code> means “is not” in R, so that the statement <code>!is.na(sex)</code> is indicating that we want to keep the data where sex <strong>is not</strong> missing.</p>
<p>In this dataset, there are no missing values for “sex,” but it is a good habit to include this condition so you are using the correct denominator if your dataset does have missing values.</p>
<p>This tells you that you had 386 observations, and there were 205 where sex was coded as 1, an observation proportion of 0.53. Now the “assumed” proportion was 0.5, giving an expected number of 193 women. These two values are quite close and the p-value is 0.2.</p>
</div>
</div>
</div>
<div id="assignments-2" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Assignments</h2>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="week-3.html#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Copy and paste this code to load the data for week 3 assignments</span></span>
<span id="cb128-2"><a href="week-3.html#cb128-2" aria-hidden="true" tabindex="-1"></a>lesson3a <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 3&quot;</span>, <span class="st">&quot;lesson3a.rds&quot;</span>))</span>
<span id="cb128-3"><a href="week-3.html#cb128-3" aria-hidden="true" tabindex="-1"></a>lesson3b <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 3&quot;</span>, <span class="st">&quot;lesson3b.rds&quot;</span>))</span>
<span id="cb128-4"><a href="week-3.html#cb128-4" aria-hidden="true" tabindex="-1"></a>lesson3c <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 3&quot;</span>, <span class="st">&quot;lesson3c.rds&quot;</span>))</span>
<span id="cb128-5"><a href="week-3.html#cb128-5" aria-hidden="true" tabindex="-1"></a>lesson3d <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 3&quot;</span>, <span class="st">&quot;lesson3d.rds&quot;</span>))</span>
<span id="cb128-6"><a href="week-3.html#cb128-6" aria-hidden="true" tabindex="-1"></a>lesson3e <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 3&quot;</span>, <span class="st">&quot;lesson3e.rds&quot;</span>))</span>
<span id="cb128-7"><a href="week-3.html#cb128-7" aria-hidden="true" tabindex="-1"></a>lesson3f <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 3&quot;</span>, <span class="st">&quot;lesson3f.rds&quot;</span>))</span></code></pre></div>
<p>Again, more questions than you need to do, unless you’re keen (also, most won’t take long). Try to do at least the first three.</p>
<ul>
<li>lesson3a.rds: These are data from over 1000 patients undergoing chemotherapy reporting a nausea and vomiting score from 0 to 10 on the day of treatment. Does previous chemotherapy increase nausea scores? What about sex?</li>
<li>lesson3b.rds: Patients with wrist osteoarthritis are randomized to a new drug or placebo. Pain is measured before and two hours after taking a dose of the drug. Is the drug effective?</li>
<li>lesson3c.rds: Some postoperative pain data again. Is pain on day 2 different than pain on day 1? Is pain on day 3 different from pain on day 2?</li>
<li>lesson3d.rds: This is a single-arm, uncontrolled study of acupuncture for patients with neck pain. Does acupuncture increase range of motion? Just as many men as women get neck pain. Can we say anything about the sample chosen for this trial with respect to gender? The mean age of patients with neck pain is 58.2 years. Is the trial population representative with respect to age?</li>
<li>lesson3e.rds: These data are length of stay from two different hospitals. One of the hospitals uses a new chemotherapy regimen that is said to reduce adverse events and therefore length of stay. Does the new regimen decrease length of stay?</li>
<li>lesson3f.rds: These data are from a randomized trial on the effects of physiotherapy treatment on physical function in pediatric patients recovering from cancer surgery. Function is measured on a 100 point scale. Does physiotherapy help improve physical functioning?</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-4.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://www.github.com/emilyvertosick/Statistics-Course/edit/master/03-week3.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
