<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Week 1 | MSKCC Biostatistics Course</title>
  <meta name="description" content="Statistics Course" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Week 1 | MSKCC Biostatistics Course" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Statistics Course" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Week 1 | MSKCC Biostatistics Course" />
  
  <meta name="twitter:description" content="Statistics Course" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="week-2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>General Course Materials</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-outline"><i class="fa fa-check"></i>Course Outline</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#andrews-contact-details"><i class="fa fa-check"></i>Andrew’s Contact Details</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#passing-the-course"><i class="fa fa-check"></i>Passing the Course</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#data-checking-procedures"><i class="fa fa-check"></i>Data Checking Procedures</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#guidelines-for-presentation-of-statistics"><i class="fa fa-check"></i>Guidelines for presentation of statistics</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1.html"><a href="week-1.html"><i class="fa fa-check"></i><b>1</b> Week 1</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1.html"><a href="week-1.html#setting-up"><i class="fa fa-check"></i><b>1.1</b> Setting Up</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="week-1.html"><a href="week-1.html#software-installation"><i class="fa fa-check"></i><b>1.1.1</b> Software Installation</a></li>
<li class="chapter" data-level="1.1.2" data-path="week-1.html"><a href="week-1.html#setting-up-course-files"><i class="fa fa-check"></i><b>1.1.2</b> Setting up course files</a></li>
<li class="chapter" data-level="1.1.3" data-path="week-1.html"><a href="week-1.html#using-rstudio"><i class="fa fa-check"></i><b>1.1.3</b> Using RStudio</a></li>
<li class="chapter" data-level="1.1.4" data-path="week-1.html"><a href="week-1.html#installing-packages"><i class="fa fa-check"></i><b>1.1.4</b> Installing packages</a></li>
<li class="chapter" data-level="1.1.5" data-path="week-1.html"><a href="week-1.html#a-note-about-packages"><i class="fa fa-check"></i><b>1.1.5</b> A Note About Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="week-1.html"><a href="week-1.html#r-instructions"><i class="fa fa-check"></i><b>1.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="week-1.html"><a href="week-1.html#opening-a-data-file-created-by-someone-else"><i class="fa fa-check"></i><b>1.2.1</b> Opening a data file created by someone else</a></li>
<li class="chapter" data-level="1.2.2" data-path="week-1.html"><a href="week-1.html#loading-packages"><i class="fa fa-check"></i><b>1.2.2</b> Loading packages</a></li>
<li class="chapter" data-level="1.2.3" data-path="week-1.html"><a href="week-1.html#looking-at-the-data"><i class="fa fa-check"></i><b>1.2.3</b> Looking at the data</a></li>
<li class="chapter" data-level="1.2.4" data-path="week-1.html"><a href="week-1.html#typing-a-command"><i class="fa fa-check"></i><b>1.2.4</b> Typing a command</a></li>
<li class="chapter" data-level="1.2.5" data-path="week-1.html"><a href="week-1.html#some-useful-commands"><i class="fa fa-check"></i><b>1.2.5</b> Some Useful Commands</a></li>
<li class="chapter" data-level="1.2.6" data-path="week-1.html"><a href="week-1.html#using-help"><i class="fa fa-check"></i><b>1.2.6</b> Using Help</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="week-1.html"><a href="week-1.html#assignments"><i class="fa fa-check"></i><b>1.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>2</b> Week 2</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-2.html"><a href="week-2.html#setting-up-1"><i class="fa fa-check"></i><b>2.1</b> Setting Up</a></li>
<li class="chapter" data-level="2.2" data-path="week-2.html"><a href="week-2.html#r-instructions-1"><i class="fa fa-check"></i><b>2.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="week-2.html"><a href="week-2.html#looking-at-your-data"><i class="fa fa-check"></i><b>2.2.1</b> Looking at your data</a></li>
<li class="chapter" data-level="2.2.2" data-path="week-2.html"><a href="week-2.html#summarizing-continuous-variables"><i class="fa fa-check"></i><b>2.2.2</b> Summarizing continuous variables</a></li>
<li class="chapter" data-level="2.2.3" data-path="week-2.html"><a href="week-2.html#centiles"><i class="fa fa-check"></i><b>2.2.3</b> Centiles</a></li>
<li class="chapter" data-level="2.2.4" data-path="week-2.html"><a href="week-2.html#one-way-tables"><i class="fa fa-check"></i><b>2.2.4</b> One-way tables</a></li>
<li class="chapter" data-level="2.2.5" data-path="week-2.html"><a href="week-2.html#two-way-tables"><i class="fa fa-check"></i><b>2.2.5</b> Two-way tables</a></li>
<li class="chapter" data-level="2.2.6" data-path="week-2.html"><a href="week-2.html#subsetting-data"><i class="fa fa-check"></i><b>2.2.6</b> Subsetting Data</a></li>
<li class="chapter" data-level="2.2.7" data-path="week-2.html"><a href="week-2.html#graphing"><i class="fa fa-check"></i><b>2.2.7</b> Graphing</a></li>
<li class="chapter" data-level="2.2.8" data-path="week-2.html"><a href="week-2.html#further-reading"><i class="fa fa-check"></i><b>2.2.8</b> Further Reading</a></li>
<li class="chapter" data-level="2.2.9" data-path="week-2.html"><a href="week-2.html#using-r-as-a-calculator"><i class="fa fa-check"></i><b>2.2.9</b> Using R as a calculator</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="week-2.html"><a href="week-2.html#assignments-1"><i class="fa fa-check"></i><b>2.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i><b>3</b> Week 3</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-3.html"><a href="week-3.html#setting-up-2"><i class="fa fa-check"></i><b>3.1</b> Setting up</a></li>
<li class="chapter" data-level="3.2" data-path="week-3.html"><a href="week-3.html#r-instructions-2"><i class="fa fa-check"></i><b>3.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="week-3.html"><a href="week-3.html#example-datasets"><i class="fa fa-check"></i><b>3.2.1</b> Example Datasets</a></li>
<li class="chapter" data-level="3.2.2" data-path="week-3.html"><a href="week-3.html#hypothesis-testing"><i class="fa fa-check"></i><b>3.2.2</b> Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="week-3.html"><a href="week-3.html#assignments-2"><i class="fa fa-check"></i><b>3.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>4</b> Week 4</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-4.html"><a href="week-4.html#setting-up-3"><i class="fa fa-check"></i><b>4.1</b> Setting Up</a></li>
<li class="chapter" data-level="4.2" data-path="week-4.html"><a href="week-4.html#r-instructions-3"><i class="fa fa-check"></i><b>4.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="week-4.html"><a href="week-4.html#tables-1"><i class="fa fa-check"></i><b>4.2.1</b> Tables</a></li>
<li class="chapter" data-level="4.2.2" data-path="week-4.html"><a href="week-4.html#getting-estimates-risk-difference-risk-ratio-odds-ratio"><i class="fa fa-check"></i><b>4.2.2</b> Getting estimates: risk difference, risk ratio, odds ratio</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="week-4.html"><a href="week-4.html#assignments-3"><i class="fa fa-check"></i><b>4.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>5</b> Week 5</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-5.html"><a href="week-5.html#setting-up-4"><i class="fa fa-check"></i><b>5.1</b> Setting Up</a></li>
<li class="chapter" data-level="5.2" data-path="week-5.html"><a href="week-5.html#r-instructions-4"><i class="fa fa-check"></i><b>5.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="week-5.html"><a href="week-5.html#correlation"><i class="fa fa-check"></i><b>5.2.1</b> Correlation</a></li>
<li class="chapter" data-level="5.2.2" data-path="week-5.html"><a href="week-5.html#linear-regression"><i class="fa fa-check"></i><b>5.2.2</b> Linear regression</a></li>
<li class="chapter" data-level="5.2.3" data-path="week-5.html"><a href="week-5.html#graphing-the-data"><i class="fa fa-check"></i><b>5.2.3</b> Graphing the data</a></li>
<li class="chapter" data-level="5.2.4" data-path="week-5.html"><a href="week-5.html#logistic-regression"><i class="fa fa-check"></i><b>5.2.4</b> Logistic regression</a></li>
<li class="chapter" data-level="5.2.5" data-path="week-5.html"><a href="week-5.html#getting-the-area-under-the-curve"><i class="fa fa-check"></i><b>5.2.5</b> Getting the area-under-the-curve</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="week-5.html"><a href="week-5.html#assignments-4"><i class="fa fa-check"></i><b>5.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>6</b> Week 6</a>
<ul>
<li class="chapter" data-level="6.1" data-path="week-6.html"><a href="week-6.html#setting-up-5"><i class="fa fa-check"></i><b>6.1</b> Setting Up</a></li>
<li class="chapter" data-level="6.2" data-path="week-6.html"><a href="week-6.html#r-instructions-5"><i class="fa fa-check"></i><b>6.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="week-6.html"><a href="week-6.html#diagnostic-tests"><i class="fa fa-check"></i><b>6.2.1</b> Diagnostic Tests</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="week-6.html"><a href="week-6.html#assignments-5"><i class="fa fa-check"></i><b>6.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>7</b> Week 7</a>
<ul>
<li class="chapter" data-level="7.1" data-path="week-7.html"><a href="week-7.html#setting-up-6"><i class="fa fa-check"></i><b>7.1</b> Setting Up</a></li>
<li class="chapter" data-level="7.2" data-path="week-7.html"><a href="week-7.html#r-instructions-6"><i class="fa fa-check"></i><b>7.2</b> R Instructions</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="week-7.html"><a href="week-7.html#introductory-remarks-on-time-to-event-analysis"><i class="fa fa-check"></i><b>7.2.1</b> Introductory remarks on time-to-event analysis</a></li>
<li class="chapter" data-level="7.2.2" data-path="week-7.html"><a href="week-7.html#time-to-event-data"><i class="fa fa-check"></i><b>7.2.2</b> Time to event data</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="week-7.html"><a href="week-7.html#assignments-6"><i class="fa fa-check"></i><b>7.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8.html"><a href="week-8.html"><i class="fa fa-check"></i><b>8</b> Week 8</a></li>
<li class="chapter" data-level="9" data-path="assignment-answers.html"><a href="assignment-answers.html"><i class="fa fa-check"></i><b>9</b> Assignment Answers</a>
<ul>
<li class="chapter" data-level="9.1" data-path="assignment-answers.html"><a href="assignment-answers.html#week-1-1"><i class="fa fa-check"></i><b>9.1</b> Week 1</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson1a"><i class="fa fa-check"></i><b>9.1.1</b> lesson1a</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="assignment-answers.html"><a href="assignment-answers.html#week-2-1"><i class="fa fa-check"></i><b>9.2</b> Week 2</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2a"><i class="fa fa-check"></i><b>9.2.1</b> lesson2a</a></li>
<li class="chapter" data-level="9.2.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2b"><i class="fa fa-check"></i><b>9.2.2</b> lesson2b</a></li>
<li class="chapter" data-level="9.2.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2c"><i class="fa fa-check"></i><b>9.2.3</b> lesson2c</a></li>
<li class="chapter" data-level="9.2.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2d"><i class="fa fa-check"></i><b>9.2.4</b> lesson2d</a></li>
<li class="chapter" data-level="9.2.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2e"><i class="fa fa-check"></i><b>9.2.5</b> lesson2e</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="assignment-answers.html"><a href="assignment-answers.html#week-3-1"><i class="fa fa-check"></i><b>9.3</b> Week 3</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3a"><i class="fa fa-check"></i><b>9.3.1</b> lesson3a</a></li>
<li class="chapter" data-level="9.3.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3b"><i class="fa fa-check"></i><b>9.3.2</b> lesson3b</a></li>
<li class="chapter" data-level="9.3.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3c"><i class="fa fa-check"></i><b>9.3.3</b> lesson3c</a></li>
<li class="chapter" data-level="9.3.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3d"><i class="fa fa-check"></i><b>9.3.4</b> lesson3d</a></li>
<li class="chapter" data-level="9.3.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3e"><i class="fa fa-check"></i><b>9.3.5</b> lesson3e</a></li>
<li class="chapter" data-level="9.3.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3f"><i class="fa fa-check"></i><b>9.3.6</b> lesson3f</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="assignment-answers.html"><a href="assignment-answers.html#week-4-1"><i class="fa fa-check"></i><b>9.4</b> Week 4</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4a"><i class="fa fa-check"></i><b>9.4.1</b> lesson4a</a></li>
<li class="chapter" data-level="9.4.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4b"><i class="fa fa-check"></i><b>9.4.2</b> lesson4b</a></li>
<li class="chapter" data-level="9.4.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4c"><i class="fa fa-check"></i><b>9.4.3</b> lesson4c</a></li>
<li class="chapter" data-level="9.4.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4d"><i class="fa fa-check"></i><b>9.4.4</b> lesson4d</a></li>
<li class="chapter" data-level="9.4.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4e"><i class="fa fa-check"></i><b>9.4.5</b> lesson4e</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="assignment-answers.html"><a href="assignment-answers.html#week-5-1"><i class="fa fa-check"></i><b>9.5</b> Week 5</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5a"><i class="fa fa-check"></i><b>9.5.1</b> lesson5a</a></li>
<li class="chapter" data-level="9.5.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5b"><i class="fa fa-check"></i><b>9.5.2</b> lesson5b</a></li>
<li class="chapter" data-level="9.5.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5c"><i class="fa fa-check"></i><b>9.5.3</b> lesson5c</a></li>
<li class="chapter" data-level="9.5.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5d"><i class="fa fa-check"></i><b>9.5.4</b> lesson5d</a></li>
<li class="chapter" data-level="9.5.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5e"><i class="fa fa-check"></i><b>9.5.5</b> lesson5e</a></li>
<li class="chapter" data-level="9.5.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5f"><i class="fa fa-check"></i><b>9.5.6</b> lesson5f</a></li>
<li class="chapter" data-level="9.5.7" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5g"><i class="fa fa-check"></i><b>9.5.7</b> lesson5g</a></li>
<li class="chapter" data-level="9.5.8" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5h"><i class="fa fa-check"></i><b>9.5.8</b> lesson5h</a></li>
<li class="chapter" data-level="9.5.9" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5i"><i class="fa fa-check"></i><b>9.5.9</b> lesson5i</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="assignment-answers.html"><a href="assignment-answers.html#week-6-1"><i class="fa fa-check"></i><b>9.6</b> Week 6</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6a-and-lesson6b"><i class="fa fa-check"></i><b>9.6.1</b> lesson6a and lesson6b</a></li>
<li class="chapter" data-level="9.6.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6c"><i class="fa fa-check"></i><b>9.6.2</b> lesson6c</a></li>
<li class="chapter" data-level="9.6.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6d"><i class="fa fa-check"></i><b>9.6.3</b> lesson6d</a></li>
<li class="chapter" data-level="9.6.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6e"><i class="fa fa-check"></i><b>9.6.4</b> lesson6e</a></li>
<li class="chapter" data-level="9.6.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6f"><i class="fa fa-check"></i><b>9.6.5</b> lesson6f</a></li>
<li class="chapter" data-level="9.6.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6g"><i class="fa fa-check"></i><b>9.6.6</b> lesson6g</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="assignment-answers.html"><a href="assignment-answers.html#week-7-1"><i class="fa fa-check"></i><b>9.7</b> Week 7</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7a"><i class="fa fa-check"></i><b>9.7.1</b> lesson7a</a></li>
<li class="chapter" data-level="9.7.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7b"><i class="fa fa-check"></i><b>9.7.2</b> lesson7b</a></li>
<li class="chapter" data-level="9.7.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7c"><i class="fa fa-check"></i><b>9.7.3</b> lesson7c</a></li>
<li class="chapter" data-level="9.7.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7d"><i class="fa fa-check"></i><b>9.7.4</b> lesson7d</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="exam.html"><a href="exam.html"><i class="fa fa-check"></i><b>10</b> Exam</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MSKCC Biostatistics Course</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-1" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">1</span> Week 1<a href="week-1.html#week-1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="setting-up" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Setting Up<a href="week-1.html#setting-up" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As a note about this book - you can copy and paste code referenced in this book by hovering over the gray box containing the code, and clicking on the icon that appears in the top right corner.</p>
<p><img src="images/copycode.PNG" /></p>
<div id="software-installation" class="section level3 hasAnchor" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Software Installation<a href="week-1.html#software-installation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Note: you’ll need to put aside 20 - 30 minutes to install the software on your computer.</p>
<p><strong>R</strong></p>
<p>Install a pre-compiled binary of R for your OS from here by clicking on “Download R for [your operating system]”:
<a href="https://cloud.r-project.org" class="uri">https://cloud.r-project.org</a></p>
<p><strong>RStudio</strong></p>
<p>Install RStudio Desktop by selecting the installer for your operating system under “Desktop Version”:</p>
<p><a href="https://www.rstudio.com/products/rstudio/download/preview/" class="uri">https://www.rstudio.com/products/rstudio/download/preview/</a></p>
</div>
<div id="setting-up-course-files" class="section level3 hasAnchor" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Setting up course files<a href="week-1.html#setting-up-course-files" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To access this course, download the “Statistics Course Data.zip” file <a href="https://github.com/emilyvertosick/Statistics-Course/blob/master/Statistics%20Course%20Data.zip?raw=true">here</a>. Create and name a folder (e.g. “MSKCC biostats course”) on your hard drive, and then unzip the file and save it in that folder. Open the “Statistics Course” folder and click to open the R project file called “Statistics Course.Rproj”. Opening this file will open RStudio (once you have it installed), and you can easily access all files from the “files” tab in the bottom right panel in RStudio.</p>
<p>There is a “Data” folder with 7 subfolders inside, which contain the data files needed for the examples and assignments for weeks 1-7.</p>
<p>There is a code file called “Install Packages Code.R” which contains the necessary code for you to install the packages for the course (see below for more details). There is another code file called “Code templates for students.R” which includes some example code that you can adapt.</p>
<p>Every time you work on this course, you should open RStudio by opening the “Statistics Course.Rproj” file. This allows R to automatically determine the file path location for the data files so you can access them without having to make any changes to the code. It may be helpful to create a desktop shortcut to the “Statistics Course.Rproj” file so you can easily access the course materials.</p>
</div>
<div id="using-rstudio" class="section level3 hasAnchor" number="1.1.3">
<h3><span class="header-section-number">1.1.3</span> Using RStudio<a href="week-1.html#using-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When you open the “Statistics Course.Rproj” file, RStudio will open, and you will see four panes in the RStudio window (if you only see three panes, select “new file” and “New R script”).</p>
<ol style="list-style-type: decimal">
<li><p>The “console” window at the bottom left is where results will be shown if running R code from a .R file or interactively. The console window is also where you type in instructions for R. To run code in the console window, you can type or copy and paste the code and press “enter.”</p></li>
<li><p>The “source” window in the top left is where you will write out R code for your .R analysis file. To run code from the source window, highlight the lines of code you’d like to run and click the “run” button, located in the upper right corner of the source window, or use the shortcut “ctrl+enter” on your keyboard.</p></li>
<li><p>The top right panel includes several tabs. The most important tabs here are “environment”, which shows your current datasets and objects, and “history”, which shows previous commands that have been run from either the “console” or the “source” window.</p></li>
<li><p>The bottom right panel also includes several tabs. The “files” tab shows all files in your current directory. The “plots” tab is where plots will be shown if a plot is created. The “packages” tab shows all R packages that are available on your machine. The “help” tab will show help files, and help files can be searched from this tab. The “viewer” tab will show any other files that are created, for example, formatted tables.</p></li>
</ol>
<p><img src="images/rstudio_window.jpg" /></p>
</div>
<div id="installing-packages" class="section level3 hasAnchor" number="1.1.4">
<h3><span class="header-section-number">1.1.4</span> Installing packages<a href="week-1.html#installing-packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this course, you will need to install several packages which will allow you to use the set of functions included in that package. To install the necessary packages, open the “Install Packages Code.R” file. Run each line in this file by highlighting the line of code and clicking the “Run” button in the top right hand corner, or using the keyboard shortcut “ctrl-enter”. If you get the following popup message, please click “yes”. If after clicking “yes” once, the pop-up reappears, you can click “no” the second time.</p>
<p><img src="images/rinstallmsg.png" /></p>
<p>Enter one line at a time, and wait for the packages to install before entering the next line. While the package is installing, you will see a red stop sign icon at the top right corner of the “console” window. Once the stop sign icon disappears, the package installation is complete and you can install the next package. You will only have to install the packages one time.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="week-1.html#cb1-1" tabindex="-1"></a><span class="co"># Installing packages</span></span>
<span id="cb1-2"><a href="week-1.html#cb1-2" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)</span>
<span id="cb1-3"><a href="week-1.html#cb1-3" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;here&quot;</span>)</span>
<span id="cb1-4"><a href="week-1.html#cb1-4" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;skimr&quot;</span>)</span>
<span id="cb1-5"><a href="week-1.html#cb1-5" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;epiR&quot;</span>)</span>
<span id="cb1-6"><a href="week-1.html#cb1-6" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;broom&quot;</span>)</span>
<span id="cb1-7"><a href="week-1.html#cb1-7" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;pROC&quot;</span>)</span>
<span id="cb1-8"><a href="week-1.html#cb1-8" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;gmodels&quot;</span>)</span>
<span id="cb1-9"><a href="week-1.html#cb1-9" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;survival&quot;</span>)</span>
<span id="cb1-10"><a href="week-1.html#cb1-10" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;ggsurvfit&quot;</span>)</span>
<span id="cb1-11"><a href="week-1.html#cb1-11" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;gt&quot;</span>)</span></code></pre></div>
<p>If you get a message that says “These packages have more recent versions available. Which would you like to update?”, you can enter “1” in the console window and press enter. This will update all necessary packages and complete the installation.</p>
<p><img src="images/updatepackage.PNG" /></p>
<p>If you are using a Windows computer and get an error message that states <span style="color:red">Error: Could not find tools necessary to compile a package</span>, you will need to download and install the Rtools program before proceeding. The instructions are below:</p>
<ol style="list-style-type: decimal">
<li>Download the “recommended” version of Rtools (in green) from <a href="https://cran.rstudio.com/bin/windows/Rtools/">this site</a>.</li>
<li>Open the “Rtools##.exe” file and follow the installation instructions.</li>
<li>After installation is complete, close RStudio and re-open by clicking on the “Statistics Course.RProj” file.</li>
<li>Re-run the above code in the console to install the packages.</li>
</ol>
<p>We will also be installing a package called {gtsummary} written by Dan Sjoberg, a statistician at MSKCC, which can format the results from your R code into a clean, publication-ready table which can be exported in many formats, including html, pdf and Word documents. The code below will install this package.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="week-1.html#cb2-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;gtsummary&quot;</span>)</span></code></pre></div>
</div>
<div id="a-note-about-packages" class="section level3 hasAnchor" number="1.1.5">
<h3><span class="header-section-number">1.1.5</span> A Note About Packages<a href="week-1.html#a-note-about-packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>R is “open source” software. Unlike, say, Microsoft Word, where only Microsoft engineers can make changes, R packages are written by statisticians all over the world. There are hundreds of R packages available, and often there are many packages available to perform the same analyses. The packages you will use in this course have been chosen because they make coding easier, perform the necessary analyses and/or create nicely formatted output such as tables and graphs. You may work with statisticians who use different packages to perform these same analyses or to format tables and graphs. For all packages used in the course, if you give the package name to your statistician, they will be able to find and install the packages directly using the <code>install.packages</code> function as we have done above.</p>
</div>
</div>
<div id="r-instructions" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> R Instructions<a href="week-1.html#r-instructions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="opening-a-data-file-created-by-someone-else" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Opening a data file created by someone else<a href="week-1.html#opening-a-data-file-created-by-someone-else" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This is mainly what you will be doing during this course. You will be loading data from files with a “.rds” extension, which is a type of file that can be exported from R. There are two ways to do this:</p>
<ol style="list-style-type: decimal">
<li>You can load files by typing or copying the following code into the console window and pressing enter. Each lesson will have code in the “Setting Up” section that will load all data necessary to run the examples in the lesson. You can copy and paste that code into your console window and press “enter” to load the files. In the “Assignments” section, there will also be code to load the files necessary for the assignment.</li>
</ol>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="week-1.html#cb3-1" tabindex="-1"></a><span class="co"># You can copy and paste this code into the console window and press &quot;enter&quot;</span></span>
<span id="cb3-2"><a href="week-1.html#cb3-2" tabindex="-1"></a><span class="co"># to load the data needed for the week 1 examples</span></span>
<span id="cb3-3"><a href="week-1.html#cb3-3" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 1&quot;</span>, <span class="st">&quot;lesson1a.rds&quot;</span>))</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Using the “files” tab on the bottom righthand side of the RStudio window. Click on the “files” tab, and navigate to the folder where the data is stored, for example, by clicking on the “Data” folder. Click on the desired data “.rds” file. A “Load R Object” popup will appear, which allows you to change the name of the dataset when you import it. It is fine for this course to leave the dataset names as is. Clicking “OK” will load this file to your environment, which you can confirm by looking for the dataset in the top right “environment” tab.</li>
</ol>
<p><img src="images/load_data.jpg" />
<br></p>
</div>
<div id="loading-packages" class="section level3 hasAnchor" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Loading packages<a href="week-1.html#loading-packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The packages you have installed contain a number of functions. There are two ways to use the functions from these packages: by loading the package, or specifying the package name every time you use a function from that package.</p>
<p>If you attempt to use a function from a package without loading that package or specifying the package name, you will get an error.</p>
<p>As an example, the <code>skim</code> function comes from the {skimr} package. Using <code>skim</code> without loading or specifying the {skimr} package will give an error:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="week-1.html#cb4-1" tabindex="-1"></a><span class="co"># This will give an error - the &quot;skimr&quot; package isn&#39;t loaded yet</span></span>
<span id="cb4-2"><a href="week-1.html#cb4-2" tabindex="-1"></a><span class="fu">skim</span>(lesson1a<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>## Error in skim(lesson1a$age): could not find function &quot;skim&quot;</code></pre>
<p>You can give both the package name and function name to avoid this error:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="week-1.html#cb6-1" tabindex="-1"></a><span class="co"># You can use the function &quot;skim&quot; by specifying package &quot;skimr&quot;</span></span>
<span id="cb6-2"><a href="week-1.html#cb6-2" tabindex="-1"></a>skimr<span class="sc">::</span><span class="fu">skim</span>(lesson1a<span class="sc">$</span>age)</span></code></pre></div>
<table>
<caption><span id="tab:loadpkgs2">Table 1.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">lesson1a$age</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">386</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="18%" />
<col width="13%" />
<col width="18%" />
<col width="7%" />
<col width="7%" />
<col width="3%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="6%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">data</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">49.48</td>
<td align="right">13.75</td>
<td align="right">19</td>
<td align="right">40</td>
<td align="right">49</td>
<td align="right">59</td>
<td align="right">86</td>
<td align="left">▃▇▇▅▁</td>
</tr>
</tbody>
</table>
<p>However, for commonly used packages, it is easier to load the whole package so you do not need to type out the package name every time you use a function. Packages are loaded by typing the package name into the <code>library</code> function. While you only need to install the packages once, you will need to load any packages you want to use every time you open up the “Statistics Course.Rproj” file in RStudio. For example, to load the {skimr} package, type or copy and paste the following line of code into the console window, and press enter.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="week-1.html#cb7-1" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code></pre></div>
<p>Now you will be able to use all functions in the {skimr} package without specifying the package name each time. Below is R code that will load all the packages you will need to use in this course. You can copy and paste these lines into your console window every time you start working in RStudio (so if you keep RStudio open, say on your laptop, you won’t generally have to reload packages). This code will also be available at the beginning of each lesson.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="week-1.html#cb8-1" tabindex="-1"></a><span class="co"># Here is the code to load all necessary packages</span></span>
<span id="cb8-2"><a href="week-1.html#cb8-2" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb8-3"><a href="week-1.html#cb8-3" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb8-4"><a href="week-1.html#cb8-4" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb8-5"><a href="week-1.html#cb8-5" tabindex="-1"></a><span class="fu">library</span>(epiR)</span>
<span id="cb8-6"><a href="week-1.html#cb8-6" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb8-7"><a href="week-1.html#cb8-7" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb8-8"><a href="week-1.html#cb8-8" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span>
<span id="cb8-9"><a href="week-1.html#cb8-9" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb8-10"><a href="week-1.html#cb8-10" tabindex="-1"></a><span class="fu">library</span>(ggsurvfit)</span>
<span id="cb8-11"><a href="week-1.html#cb8-11" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
</div>
<div id="looking-at-the-data" class="section level3 hasAnchor" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Looking at the data<a href="week-1.html#looking-at-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>R stores the data in the form of a spreadsheet. The rows are individual observations, normally a patient. The columns are variables giving data for that observation. View the dataset <strong>lesson1a</strong> by typing the following into the console window and hitting enter (a new window will pop up):</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="week-1.html#cb9-1" tabindex="-1"></a><span class="co"># View the data as a spreadsheet</span></span>
<span id="cb9-2"><a href="week-1.html#cb9-2" tabindex="-1"></a><span class="fu">View</span>(lesson1a)</span></code></pre></div>
<p>This is data from 386 patients undergoing surgery. You can see the patient’s hospital code number as the variable “id” and then their age and sex. There are then lists of other variables with names such as “p1”, “t”, “x” and so on. You can see that you can have both numbers and text as a variable. You may also notice that some variables have a value of “NA” for a particular observation (e.g. the 3rd and 4th observations for variable “z”). In R, “NA” indicates missing data.</p>
</div>
<div id="typing-a-command" class="section level3 hasAnchor" number="1.2.4">
<h3><span class="header-section-number">1.2.4</span> Typing a command<a href="week-1.html#typing-a-command" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are two options to run R code: you can type or copy and paste code into either the “console” window or the “source” window. To run code from the “console” window, simply press “enter”. To run code from the “source” window, highlight the code you would like to run, and click the “run” button (top right corner of the “source” window) or use the keyboard shortcut “ctrl+enter”.</p>
<p>A typical command is of the form: <code>packagename::function(options)</code>. If a package has already been loaded using the <code>library</code> function (as we did above), you can omit <code>packagename::</code> when running the code.</p>
<p>Since you can have multiple datasets in R at the same time, your command must indicate which dataset you are referring to. This is usually done by including the dataset name inside the parentheses of the function.</p>
<p>For example, this will summarize the data for the full <strong>lesson1a</strong> dataset.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="week-1.html#cb10-1" tabindex="-1"></a><span class="co"># View a summary of the dataset</span></span>
<span id="cb10-2"><a href="week-1.html#cb10-2" tabindex="-1"></a><span class="fu">skim</span>(lesson1a)</span></code></pre></div>
<p>The output above this text is the code, and the output below this shows the results produced by running that code. (We will discuss the results output in more detail later.)</p>
<table>
<caption>(#tab:section1b_1a)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">lesson1a</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">386</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">10</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<colgroup>
<col width="19%" />
<col width="13%" />
<col width="19%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="12%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">y</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">9</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="13%" />
<col width="9%" />
<col width="13%" />
<col width="9%" />
<col width="9%" />
<col width="6%" />
<col width="8%" />
<col width="6%" />
<col width="8%" />
<col width="6%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">id</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">559159.34</td>
<td align="right">257028.45</td>
<td align="right">101143</td>
<td align="right">337803.5</td>
<td align="right">564405</td>
<td align="right">778010.8</td>
<td align="right">999214</td>
<td align="left">▆▇▇▇▇</td>
</tr>
<tr class="even">
<td align="left">sex</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.53</td>
<td align="right">0.50</td>
<td align="right">0</td>
<td align="right">0.0</td>
<td align="right">1</td>
<td align="right">1.0</td>
<td align="right">1</td>
<td align="left">▇▁▁▁▇</td>
</tr>
<tr class="odd">
<td align="left">age</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">49.48</td>
<td align="right">13.75</td>
<td align="right">19</td>
<td align="right">40.0</td>
<td align="right">49</td>
<td align="right">59.0</td>
<td align="right">86</td>
<td align="left">▃▇▇▅▁</td>
</tr>
<tr class="even">
<td align="left">p1</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3.24</td>
<td align="right">1.66</td>
<td align="right">0</td>
<td align="right">2.0</td>
<td align="right">3</td>
<td align="right">5.0</td>
<td align="right">6</td>
<td align="left">▆▂▇▅▇</td>
</tr>
<tr class="odd">
<td align="left">p2</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3.29</td>
<td align="right">1.59</td>
<td align="right">0</td>
<td align="right">2.0</td>
<td align="right">3</td>
<td align="right">5.0</td>
<td align="right">6</td>
<td align="left">▆▂▇▆▇</td>
</tr>
<tr class="even">
<td align="left">p3</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">3.09</td>
<td align="right">1.63</td>
<td align="right">0</td>
<td align="right">2.0</td>
<td align="right">3</td>
<td align="right">4.0</td>
<td align="right">6</td>
<td align="left">▇▃▇▆▇</td>
</tr>
<tr class="odd">
<td align="left">p4</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">2.62</td>
<td align="right">1.63</td>
<td align="right">0</td>
<td align="right">1.0</td>
<td align="right">3</td>
<td align="right">4.0</td>
<td align="right">6</td>
<td align="left">▇▂▇▅▃</td>
</tr>
<tr class="even">
<td align="left">t</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">12.24</td>
<td align="right">5.75</td>
<td align="right">0</td>
<td align="right">8.0</td>
<td align="right">12</td>
<td align="right">17.0</td>
<td align="right">24</td>
<td align="left">▃▅▇▇▃</td>
</tr>
<tr class="odd">
<td align="left">x</td>
<td align="right">2</td>
<td align="right">0.99</td>
<td align="right">1.54</td>
<td align="right">0.50</td>
<td align="right">1</td>
<td align="right">1.0</td>
<td align="right">2</td>
<td align="right">2.0</td>
<td align="right">2</td>
<td align="left">▇▁▁▁▇</td>
</tr>
<tr class="even">
<td align="left">z</td>
<td align="right">2</td>
<td align="right">0.99</td>
<td align="right">1.59</td>
<td align="right">0.84</td>
<td align="right">1</td>
<td align="right">1.0</td>
<td align="right">1</td>
<td align="right">2.0</td>
<td align="right">3</td>
<td align="left">▇▁▂▁▃</td>
</tr>
</tbody>
</table>
</div>
<div id="some-useful-commands" class="section level3 hasAnchor" number="1.2.5">
<h3><span class="header-section-number">1.2.5</span> Some Useful Commands<a href="week-1.html#some-useful-commands" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="extracting-a-variable-by-name" class="section level4 hasAnchor" number="1.2.5.1">
<h4><span class="header-section-number">1.2.5.1</span> Extracting a variable by name ($)<a href="week-1.html#extracting-a-variable-by-name" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To refer to one variable in your dataset, you can use the notation <code>dataset$variable</code> to indicate which dataset you are referencing, and which variable within that dataset.</p>
<p>For example, this will summarize just the variable “age” from the <strong>lesson1a</strong> dataset.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="week-1.html#cb11-1" tabindex="-1"></a><span class="co"># View a summary of the &quot;age&quot; variable only</span></span>
<span id="cb11-2"><a href="week-1.html#cb11-2" tabindex="-1"></a><span class="fu">skim</span>(lesson1a<span class="sc">$</span>age)</span></code></pre></div>
<table>
<caption><span id="tab:section1c">Table 1.2: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">lesson1a$age</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">386</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="18%" />
<col width="13%" />
<col width="18%" />
<col width="7%" />
<col width="7%" />
<col width="3%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="6%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">data</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">49.48</td>
<td align="right">13.75</td>
<td align="right">19</td>
<td align="right">40</td>
<td align="right">49</td>
<td align="right">59</td>
<td align="right">86</td>
<td align="left">▃▇▇▅▁</td>
</tr>
</tbody>
</table>
</div>
<div id="pipe-operator" class="section level4 hasAnchor" number="1.2.5.2">
<h4><span class="header-section-number">1.2.5.2</span> Pipe operator (%&gt;%)<a href="week-1.html#pipe-operator" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One of the most useful commands is known as the pipe operator (%&gt;%). The pipe operator can be read as “and then”. Pipes allow a dataset to be passed from the left side of the pipe to the command on the right side. The dataset you are using will be referenced on the left side of the pipe, rather than included as an option in the next function. This notation is useful because it can make your code more clear if you are using more than one function.</p>
<p>Here is an example of piping using the <code>skim</code> function.</p>
<p>This piece of code can be read as, “Use the <code>skim</code> function on the <strong>lesson1a</strong> dataset”.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="week-1.html#cb12-1" tabindex="-1"></a><span class="co"># You can put the dataset into the function</span></span>
<span id="cb12-2"><a href="week-1.html#cb12-2" tabindex="-1"></a><span class="fu">skim</span>(lesson1a)</span></code></pre></div>
<p>This piece of code can be read as, “Take the <strong>lesson1a</strong> dataset, <strong>and then</strong> give this data to the <code>skim</code> function to use.”</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="week-1.html#cb13-1" tabindex="-1"></a><span class="co"># You can also use the &quot;pipe&quot; operator</span></span>
<span id="cb13-2"><a href="week-1.html#cb13-2" tabindex="-1"></a>lesson1a <span class="sc">%&gt;%</span> <span class="fu">skim</span>()</span></code></pre></div>
<p>You can see that both of these lines of code are doing the same thing, although the order of the function and the dataset are different. Both will give the same results - try copying both lines of code into your console window to check that this is true.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="week-1.html#cb14-1" tabindex="-1"></a><span class="co"># These two pieces of code will also give the same results</span></span>
<span id="cb14-2"><a href="week-1.html#cb14-2" tabindex="-1"></a><span class="fu">skim</span>(lesson1a<span class="sc">$</span>age)</span>
<span id="cb14-3"><a href="week-1.html#cb14-3" tabindex="-1"></a>lesson1a <span class="sc">%&gt;%</span> <span class="fu">skim</span>(age)</span></code></pre></div>
<p>In this example, the pipe operator is not particularly useful - it actually involves more typing (<code>lesson1a %&gt;% skim()</code>) than not using the pipe operator (<code>skim(lesson1a)</code>).</p>
<p>However, the pipe operator is very helpful in more complex code. Here is an example of two pieces of code that do the same thing, with the second example using the pipe notation. You don’t need to understand what this code does, but you can see that the pipe notation makes the code shorter and easier to read. It allows you to see what is happening in the code in order from left to right and top to bottom, while the code without pipes has to be read from the inside (the innermost set of parentheses) to the outside (the outermost set of parentheses).</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="week-1.html#cb15-1" tabindex="-1"></a><span class="co"># Without piping</span></span>
<span id="cb15-2"><a href="week-1.html#cb15-2" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> </span>
<span id="cb15-3"><a href="week-1.html#cb15-3" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">filter</span>(<span class="fu">mutate</span>(trial, <span class="at">trt =</span> <span class="fu">as_factor</span>(<span class="fu">str_sub</span>(<span class="fu">str_to_upper</span>(trt), <span class="dv">1</span>, <span class="dv">4</span>))), age <span class="sc">&gt;</span> <span class="dv">60</span>), trt, age, marker, stage, grade)</span>
<span id="cb15-4"><a href="week-1.html#cb15-4" tabindex="-1"></a></span>
<span id="cb15-5"><a href="week-1.html#cb15-5" tabindex="-1"></a>new_data</span></code></pre></div>
<pre><code>## # A tibble: 37 × 5
##    trt     age marker stage grade
##    &lt;fct&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;
##  1 DRUG     63  0.06  T3    I    
##  2 DRUG     71  0.445 T4    III  
##  3 DRUG     61  1.71  T4    I    
##  4 DRUG     63  0.981 T4    II   
##  5 DRUG     67  1.16  T1    II   
##  6 DRUG     68  0.105 T4    II   
##  7 DRUG     78  0.175 T3    I    
##  8 DRUG     61  0.177 T4    III  
##  9 DRUG     71  0.737 T1    I    
## 10 DRUG     83  0.475 T1    III  
## # ℹ 27 more rows</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="week-1.html#cb17-1" tabindex="-1"></a><span class="co"># With piping</span></span>
<span id="cb17-2"><a href="week-1.html#cb17-2" tabindex="-1"></a>new_data_pipe <span class="ot">&lt;-</span></span>
<span id="cb17-3"><a href="week-1.html#cb17-3" tabindex="-1"></a>  trial <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="week-1.html#cb17-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-5"><a href="week-1.html#cb17-5" tabindex="-1"></a>    <span class="at">trt =</span> <span class="fu">str_to_upper</span>(trt) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="week-1.html#cb17-6" tabindex="-1"></a>      <span class="fu">str_sub</span>(<span class="dv">1</span>, <span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="week-1.html#cb17-7" tabindex="-1"></a>      <span class="fu">as_factor</span>()</span>
<span id="cb17-8"><a href="week-1.html#cb17-8" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb17-9"><a href="week-1.html#cb17-9" tabindex="-1"></a>  <span class="fu">select</span>(trt, age, marker, stage, grade) <span class="sc">%&gt;%</span></span>
<span id="cb17-10"><a href="week-1.html#cb17-10" tabindex="-1"></a>  <span class="fu">filter</span>(age <span class="sc">&gt;</span> <span class="dv">60</span>)</span>
<span id="cb17-11"><a href="week-1.html#cb17-11" tabindex="-1"></a></span>
<span id="cb17-12"><a href="week-1.html#cb17-12" tabindex="-1"></a>new_data_pipe</span></code></pre></div>
<pre><code>## # A tibble: 37 × 5
##    trt     age marker stage grade
##    &lt;fct&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;
##  1 DRUG     63  0.06  T3    I    
##  2 DRUG     71  0.445 T4    III  
##  3 DRUG     61  1.71  T4    I    
##  4 DRUG     63  0.981 T4    II   
##  5 DRUG     67  1.16  T1    II   
##  6 DRUG     68  0.105 T4    II   
##  7 DRUG     78  0.175 T3    I    
##  8 DRUG     61  0.177 T4    III  
##  9 DRUG     71  0.737 T1    I    
## 10 DRUG     83  0.475 T1    III  
## # ℹ 27 more rows</code></pre>
</div>
<div id="assignment-operator--" class="section level4 hasAnchor" number="1.2.5.3">
<h4><span class="header-section-number">1.2.5.3</span> Assignment Operator (&lt;-)<a href="week-1.html#assignment-operator--" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The assignment operator allows you save out changes you have made, for example, changes to datasets, or new objects you have created, like a table. You can make changes to a dataset, which will print in the console window. However, you must use the assignment operator to store out these changes.</p>
<p>Below is an example of how to create a dataset that contains only patients in the “Drug A” group and how to save this dataset out. You do not need to know all of these functions at this point, although you will learn them in the future.</p>
<p><strong>Note:</strong> the <strong>trial</strong> dataset is automatically loaded when you load the {gtsummary} package, which we’ve done above, so this dataset does not have to be manually loaded like the <strong>lesson1a</strong> dataset.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="week-1.html#cb19-1" tabindex="-1"></a><span class="co"># Here we are only keeping patients from the &quot;Drug A&quot; group</span></span>
<span id="cb19-2"><a href="week-1.html#cb19-2" tabindex="-1"></a>trial <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="week-1.html#cb19-3" tabindex="-1"></a>  <span class="fu">filter</span>(trt <span class="sc">==</span> <span class="st">&quot;Drug A&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 98 × 8
##    trt      age marker stage grade response death ttdeath
##    &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;    &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;
##  1 Drug A    23  0.16  T1    II           0     0    24  
##  2 Drug A    31  0.277 T1    II           0     0    24  
##  3 Drug A    NA  2.07  T3    III          1     1    17.6
##  4 Drug A    51  2.77  T4    III          1     1    16.4
##  5 Drug A    37  0.354 T1    II           0     0    24  
##  6 Drug A    32  1.74  T1    I            0     1    18.4
##  7 Drug A    31  0.144 T1    II           0     0    24  
##  8 Drug A    38  2.08  T4    III          1     0    24  
##  9 Drug A    57  0.066 T1    III          0     0    24  
## 10 Drug A    46  0.325 T1    II           0     0    24  
## # ℹ 88 more rows</code></pre>
<p>You can see that the data that prints out only includes observations where “trt” is “Drug A”. While this dataset printed out, it no longer exists, because we did not give it a name and save it out. You can see this below - the dataset still has all observations.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="week-1.html#cb21-1" tabindex="-1"></a><span class="co"># Print original dataset to confirm no changes</span></span>
<span id="cb21-2"><a href="week-1.html#cb21-2" tabindex="-1"></a>trial</span></code></pre></div>
<pre><code>## # A tibble: 200 × 8
##    trt      age marker stage grade response death ttdeath
##    &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;    &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;
##  1 Drug A    23  0.16  T1    II           0     0    24  
##  2 Drug B     9  1.11  T2    I            1     0    24  
##  3 Drug A    31  0.277 T1    II           0     0    24  
##  4 Drug A    NA  2.07  T3    III          1     1    17.6
##  5 Drug A    51  2.77  T4    III          1     1    16.4
##  6 Drug B    39  0.613 T4    I            0     1    15.6
##  7 Drug A    37  0.354 T1    II           0     0    24  
##  8 Drug A    32  1.74  T1    I            0     1    18.4
##  9 Drug A    31  0.144 T1    II           0     0    24  
## 10 Drug B    34  0.205 T3    I            0     1    10.5
## # ℹ 190 more rows</code></pre>
<p>Sometimes, this is fine - for example, if you simply want to take a look at the data. If you need to use this data again, give the dataset a name and use the assignment operator.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="week-1.html#cb23-1" tabindex="-1"></a><span class="co"># Save out dataset including only patients in drug group</span></span>
<span id="cb23-2"><a href="week-1.html#cb23-2" tabindex="-1"></a>trial_drug <span class="ot">&lt;-</span></span>
<span id="cb23-3"><a href="week-1.html#cb23-3" tabindex="-1"></a>  trial <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="week-1.html#cb23-4" tabindex="-1"></a>  <span class="fu">filter</span>(trt <span class="sc">==</span> <span class="st">&quot;Drug A&quot;</span>)</span>
<span id="cb23-5"><a href="week-1.html#cb23-5" tabindex="-1"></a></span>
<span id="cb23-6"><a href="week-1.html#cb23-6" tabindex="-1"></a>trial_drug</span></code></pre></div>
<pre><code>## # A tibble: 98 × 8
##    trt      age marker stage grade response death ttdeath
##    &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;    &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;
##  1 Drug A    23  0.16  T1    II           0     0    24  
##  2 Drug A    31  0.277 T1    II           0     0    24  
##  3 Drug A    NA  2.07  T3    III          1     1    17.6
##  4 Drug A    51  2.77  T4    III          1     1    16.4
##  5 Drug A    37  0.354 T1    II           0     0    24  
##  6 Drug A    32  1.74  T1    I            0     1    18.4
##  7 Drug A    31  0.144 T1    II           0     0    24  
##  8 Drug A    38  2.08  T4    III          1     0    24  
##  9 Drug A    57  0.066 T1    III          0     0    24  
## 10 Drug A    46  0.325 T1    II           0     0    24  
## # ℹ 88 more rows</code></pre>
<p>Here, we’ve called this dataset <strong>trial_drug</strong>, and you can see that this dataset only includes the patients in the “Drug A” group.</p>
</div>
<div id="head-function" class="section level4 hasAnchor" number="1.2.5.4">
<h4><span class="header-section-number">1.2.5.4</span> <code>head</code> function<a href="week-1.html#head-function" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>head</code> function allows you to see the first few rows of your dataset in the console window, including the variable names and variable types at the top of the table. (Using the code <code>head(lesson1a)</code> will also give you the same results.)</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="week-1.html#cb25-1" tabindex="-1"></a><span class="co"># Look at the first few rows of your data</span></span>
<span id="cb25-2"><a href="week-1.html#cb25-2" tabindex="-1"></a>lesson1a <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 11
##       id   sex   age    p1    p2    p3    p4     t     x y             z
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
## 1 541836     0    33     0     0     0     0     0     2 campus        1
## 2 285383     1    55     0     1     1     1     3     2 campus        1
## 3 332777     0    52     0     0     3     3     6     1 campus       NA
## 4 566828     1    53     0     0     0     1     1     2 campus       NA
## 5 193254     1    57     0     1     2     3     6     2 satellite     1
## 6 530508     1    31     0     0     2     2     4     1 campus        3</code></pre>
</div>
<div id="table-function" class="section level4 hasAnchor" number="1.2.5.5">
<h4><span class="header-section-number">1.2.5.5</span> <code>table</code> function<a href="week-1.html#table-function" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>table</code> function is the basic function for creating one-way and two-way tables. However, these tables often do not provide much information and are not formatted nicely or in a way that can easily be copied to a Word document.</p>
<p>Here is an example of a one-way table using the <code>table</code> function:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="week-1.html#cb27-1" tabindex="-1"></a><span class="co"># Create one-way table for death</span></span>
<span id="cb27-2"><a href="week-1.html#cb27-2" tabindex="-1"></a><span class="fu">table</span>(trial<span class="sc">$</span>death)</span></code></pre></div>
<pre><code>## 
##   0   1 
##  88 112</code></pre>
<p>While this table does not give column names and is not formatted, you can see that it shows that there are 112 patients who died, and 88 patients who did not.</p>
<p>Here is an example of a two-way table:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="week-1.html#cb29-1" tabindex="-1"></a><span class="co"># Create two-way table for response and death</span></span>
<span id="cb29-2"><a href="week-1.html#cb29-2" tabindex="-1"></a><span class="fu">table</span>(trial<span class="sc">$</span>response, trial<span class="sc">$</span>death)</span></code></pre></div>
<pre><code>##    
##      0  1
##   0 49 83
##   1 37 24</code></pre>
<p>Unlike the one-way table, these results are not easily interpretable. If you are not familiar with R code or with your data, this table is not very useful. There is nothing to indicate which variable is represented by the columns, and which variable is represented by the rows. The table only provides counts, and does not provide any percents.</p>
<p>If you print the “response” variable, you can also see that there are “NA” values in the response variable, which the table doesn’t include at all.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="week-1.html#cb31-1" tabindex="-1"></a><span class="co"># Print response variable values</span></span>
<span id="cb31-2"><a href="week-1.html#cb31-2" tabindex="-1"></a>trial<span class="sc">$</span>response</span></code></pre></div>
<pre><code>##   [1]  0  1  0  1  1  0  0  0  0  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  0
##  [26]  0  1  0  0  1  1  0  0  1  0 NA  0  1  0  0  0  1  0  1  1  1  1  0  0  0
##  [51]  0  0  0  0  0  0  1  0  1  1  0  0  0  0 NA  0  1  1  0  0  1  0  0  0  1
##  [76]  0  0  0  0  0  0  1  0  0  0  1  0  1  0  0  0  0  1  1  1  0  0  0  0  0
## [101]  0  0 NA  0  0  1  0  0  0  0  1  1  0  0  1  1  0  0  0  0  1  0  0  0  0
## [126]  1  1  0  0  0  1  0  0  0  1  0  1  1 NA  1  1  1  0  1  0  0  1  0 NA  1
## [151]  0  0  0  0  0  0  0  0  0  1  0  0  1  1  0  0  0  1  0  1  0  1  0  1  1
## [176]  1  0  1 NA  0  1  0  0  1  0  1  0  0  0  0  0  0  0  0 NA  0  1  1  0  0
## attr(,&quot;label&quot;)
## [1] &quot;Tumor Response&quot;</code></pre>
</div>
<div id="tbl_summary-function" class="section level4 hasAnchor" number="1.2.5.6">
<h4><span class="header-section-number">1.2.5.6</span> <code>tbl_summary</code> function<a href="week-1.html#tbl_summary-function" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>tbl_summary</code> function (from the {gtsummary} package) creates and formats tables so that it is clear what the columns and rows are, and also includes any missing values. This function also formats the tables in a way that can easily be copied and pasted into a Word document for publication.</p>
<p>In this course, we will be using the <code>tbl_summary</code> function instead of the <code>table</code> function for all tables that will be displayed. There are some cases where the <code>table</code> function will be used in conjunction with another function to perform an analysis, but these tables will not be displayed.</p>
<p><strong>Note:</strong> Tables created by the <code>tbl_summary</code> package will not display in the “console” window, and will instead display in the “Viewer” pane on the bottom right-hand side of the screen.</p>
<p>The <code>tbl_summary</code> function can create one-way and two-way tables for binary and categorical variables. It can also create tables which include summary statistics for continuous variables (by default, median and quartiles). The <code>select</code> function allows you to list the variables you would like to include in your table. Here, we are only showing sex in the table.</p>
<p>Here is an example of a one-way table created using the <code>tbl_summary</code> function:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="week-1.html#cb33-1" tabindex="-1"></a><span class="co"># Create a formatted table for the &quot;sex&quot; variable</span></span>
<span id="cb33-2"><a href="week-1.html#cb33-2" tabindex="-1"></a><span class="fu">tbl_summary</span>(</span>
<span id="cb33-3"><a href="week-1.html#cb33-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span> <span class="fu">select</span>(sex) </span>
<span id="cb33-4"><a href="week-1.html#cb33-4" tabindex="-1"></a>)</span></code></pre></div>
<div id="iwrgxmosvm" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#iwrgxmosvm table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#iwrgxmosvm thead, #iwrgxmosvm tbody, #iwrgxmosvm tfoot, #iwrgxmosvm tr, #iwrgxmosvm td, #iwrgxmosvm th {
  border-style: none;
}

#iwrgxmosvm p {
  margin: 0;
  padding: 0;
}

#iwrgxmosvm .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#iwrgxmosvm .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#iwrgxmosvm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#iwrgxmosvm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#iwrgxmosvm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iwrgxmosvm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iwrgxmosvm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iwrgxmosvm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#iwrgxmosvm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#iwrgxmosvm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#iwrgxmosvm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#iwrgxmosvm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#iwrgxmosvm .gt_spanner_row {
  border-bottom-style: hidden;
}

#iwrgxmosvm .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#iwrgxmosvm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#iwrgxmosvm .gt_from_md > :first-child {
  margin-top: 0;
}

#iwrgxmosvm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#iwrgxmosvm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#iwrgxmosvm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#iwrgxmosvm .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#iwrgxmosvm .gt_row_group_first td {
  border-top-width: 2px;
}

#iwrgxmosvm .gt_row_group_first th {
  border-top-width: 2px;
}

#iwrgxmosvm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iwrgxmosvm .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#iwrgxmosvm .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#iwrgxmosvm .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iwrgxmosvm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iwrgxmosvm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#iwrgxmosvm .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#iwrgxmosvm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#iwrgxmosvm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iwrgxmosvm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iwrgxmosvm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#iwrgxmosvm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iwrgxmosvm .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#iwrgxmosvm .gt_left {
  text-align: left;
}

#iwrgxmosvm .gt_center {
  text-align: center;
}

#iwrgxmosvm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#iwrgxmosvm .gt_font_normal {
  font-weight: normal;
}

#iwrgxmosvm .gt_font_bold {
  font-weight: bold;
}

#iwrgxmosvm .gt_font_italic {
  font-style: italic;
}

#iwrgxmosvm .gt_super {
  font-size: 65%;
}

#iwrgxmosvm .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#iwrgxmosvm .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#iwrgxmosvm .gt_indent_1 {
  text-indent: 5px;
}

#iwrgxmosvm .gt_indent_2 {
  text-indent: 10px;
}

#iwrgxmosvm .gt_indent_3 {
  text-indent: 15px;
}

#iwrgxmosvm .gt_indent_4 {
  text-indent: 20px;
}

#iwrgxmosvm .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;N = 386&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>N = 386</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">1 if woman, 0 if man</td>
<td headers="stat_0" class="gt_row gt_center">205 (53%)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> n (%)</td>
    </tr>
  </tfoot>
</table>
</div>
<p>As you can see, there is currently only one row in the table. If a variable has values of 0 and 1 only, the <code>tbl_summary</code> function gives the percentage of values that are equal to 1 by default. If you would like to see the percentage of both 0 and 1 values, you can use the “type” option and specify that the variable is categorical.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="week-1.html#cb34-1" tabindex="-1"></a><span class="co"># Create a formatted table for the &quot;sex&quot; variable, showing both &quot;0&quot; and &quot;1&quot; values</span></span>
<span id="cb34-2"><a href="week-1.html#cb34-2" tabindex="-1"></a><span class="fu">tbl_summary</span>(</span>
<span id="cb34-3"><a href="week-1.html#cb34-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span> <span class="fu">select</span>(sex),</span>
<span id="cb34-4"><a href="week-1.html#cb34-4" tabindex="-1"></a>  <span class="at">type =</span> <span class="fu">list</span>(<span class="at">sex =</span> <span class="st">&quot;categorical&quot;</span>)</span>
<span id="cb34-5"><a href="week-1.html#cb34-5" tabindex="-1"></a>)</span></code></pre></div>
<div id="epqsnuprvj" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#epqsnuprvj table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#epqsnuprvj thead, #epqsnuprvj tbody, #epqsnuprvj tfoot, #epqsnuprvj tr, #epqsnuprvj td, #epqsnuprvj th {
  border-style: none;
}

#epqsnuprvj p {
  margin: 0;
  padding: 0;
}

#epqsnuprvj .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#epqsnuprvj .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#epqsnuprvj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#epqsnuprvj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#epqsnuprvj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#epqsnuprvj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#epqsnuprvj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#epqsnuprvj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#epqsnuprvj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#epqsnuprvj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#epqsnuprvj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#epqsnuprvj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#epqsnuprvj .gt_spanner_row {
  border-bottom-style: hidden;
}

#epqsnuprvj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#epqsnuprvj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#epqsnuprvj .gt_from_md > :first-child {
  margin-top: 0;
}

#epqsnuprvj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#epqsnuprvj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#epqsnuprvj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#epqsnuprvj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#epqsnuprvj .gt_row_group_first td {
  border-top-width: 2px;
}

#epqsnuprvj .gt_row_group_first th {
  border-top-width: 2px;
}

#epqsnuprvj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#epqsnuprvj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#epqsnuprvj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#epqsnuprvj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#epqsnuprvj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#epqsnuprvj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#epqsnuprvj .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#epqsnuprvj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#epqsnuprvj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#epqsnuprvj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#epqsnuprvj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#epqsnuprvj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#epqsnuprvj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#epqsnuprvj .gt_left {
  text-align: left;
}

#epqsnuprvj .gt_center {
  text-align: center;
}

#epqsnuprvj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#epqsnuprvj .gt_font_normal {
  font-weight: normal;
}

#epqsnuprvj .gt_font_bold {
  font-weight: bold;
}

#epqsnuprvj .gt_font_italic {
  font-style: italic;
}

#epqsnuprvj .gt_super {
  font-size: 65%;
}

#epqsnuprvj .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#epqsnuprvj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#epqsnuprvj .gt_indent_1 {
  text-indent: 5px;
}

#epqsnuprvj .gt_indent_2 {
  text-indent: 10px;
}

#epqsnuprvj .gt_indent_3 {
  text-indent: 15px;
}

#epqsnuprvj .gt_indent_4 {
  text-indent: 20px;
}

#epqsnuprvj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;N = 386&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>N = 386</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">1 if woman, 0 if man</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    0</td>
<td headers="stat_0" class="gt_row gt_center">181 (47%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    1</td>
<td headers="stat_0" class="gt_row gt_center">205 (53%)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> n (%)</td>
    </tr>
  </tfoot>
</table>
</div>
<p><br></p>
<p>This tells you that the “sex” variable has no missing data because the table only shows values of “0” and “1”, with no “NA” values. It also shows that there only 2 different values, all of which are integers (i.e. whole numbers). Now this is useful because if you had been sent a set of data for sex and the <code>tbl_summary</code> function told you that there were 4 unique values, some of which were not integers, you would want to check the data further before doing any analysis.</p>
<p>Since 0 = man and 1 = woman based on the variable label (see the first row of the table), this means that there were 181 men in the 386 patients and that they constituted 47% of the population.</p>
<p>The <code>tbl_summary</code> function can also be used for two-way tables. The <code>select</code> function is used to select both variables of interest, and the name of the column variable is specified in the <code>by</code> statement. As you can see, this table is much clearer, as well as nicer looking, than the table created by the <code>table</code> function. It also includes information on the missing (NA) values, which are excluded when using the <code>table</code> function.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="week-1.html#cb35-1" tabindex="-1"></a><span class="co"># Create two-way table for response and death using &quot;table&quot; function</span></span>
<span id="cb35-2"><a href="week-1.html#cb35-2" tabindex="-1"></a><span class="fu">table</span>(trial<span class="sc">$</span>response, trial<span class="sc">$</span>death)</span></code></pre></div>
<pre><code>##    
##      0  1
##   0 49 83
##   1 37 24</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="week-1.html#cb37-1" tabindex="-1"></a><span class="co"># Create two-way table for response and death using &quot;tbl_summary&quot; function</span></span>
<span id="cb37-2"><a href="week-1.html#cb37-2" tabindex="-1"></a><span class="fu">tbl_summary</span>(</span>
<span id="cb37-3"><a href="week-1.html#cb37-3" tabindex="-1"></a>  trial <span class="sc">%&gt;%</span> <span class="fu">select</span>(response, death),</span>
<span id="cb37-4"><a href="week-1.html#cb37-4" tabindex="-1"></a>  <span class="at">by =</span> death,</span>
<span id="cb37-5"><a href="week-1.html#cb37-5" tabindex="-1"></a>  <span class="at">type =</span> <span class="fu">list</span>(<span class="at">response =</span> <span class="st">&quot;categorical&quot;</span>)</span>
<span id="cb37-6"><a href="week-1.html#cb37-6" tabindex="-1"></a>)</span></code></pre></div>
<div id="ptgxhgemkg" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ptgxhgemkg table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ptgxhgemkg thead, #ptgxhgemkg tbody, #ptgxhgemkg tfoot, #ptgxhgemkg tr, #ptgxhgemkg td, #ptgxhgemkg th {
  border-style: none;
}

#ptgxhgemkg p {
  margin: 0;
  padding: 0;
}

#ptgxhgemkg .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ptgxhgemkg .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ptgxhgemkg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ptgxhgemkg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ptgxhgemkg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ptgxhgemkg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ptgxhgemkg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ptgxhgemkg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ptgxhgemkg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ptgxhgemkg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ptgxhgemkg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ptgxhgemkg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ptgxhgemkg .gt_spanner_row {
  border-bottom-style: hidden;
}

#ptgxhgemkg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ptgxhgemkg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ptgxhgemkg .gt_from_md > :first-child {
  margin-top: 0;
}

#ptgxhgemkg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ptgxhgemkg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ptgxhgemkg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ptgxhgemkg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ptgxhgemkg .gt_row_group_first td {
  border-top-width: 2px;
}

#ptgxhgemkg .gt_row_group_first th {
  border-top-width: 2px;
}

#ptgxhgemkg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ptgxhgemkg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ptgxhgemkg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ptgxhgemkg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ptgxhgemkg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ptgxhgemkg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ptgxhgemkg .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ptgxhgemkg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ptgxhgemkg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ptgxhgemkg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ptgxhgemkg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ptgxhgemkg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ptgxhgemkg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ptgxhgemkg .gt_left {
  text-align: left;
}

#ptgxhgemkg .gt_center {
  text-align: center;
}

#ptgxhgemkg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ptgxhgemkg .gt_font_normal {
  font-weight: normal;
}

#ptgxhgemkg .gt_font_bold {
  font-weight: bold;
}

#ptgxhgemkg .gt_font_italic {
  font-style: italic;
}

#ptgxhgemkg .gt_super {
  font-size: 65%;
}

#ptgxhgemkg .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ptgxhgemkg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ptgxhgemkg .gt_indent_1 {
  text-indent: 5px;
}

#ptgxhgemkg .gt_indent_2 {
  text-indent: 10px;
}

#ptgxhgemkg .gt_indent_3 {
  text-indent: 15px;
}

#ptgxhgemkg .gt_indent_4 {
  text-indent: 20px;
}

#ptgxhgemkg .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;0&lt;/strong&gt;, N = 88&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>0</strong>, N = 88<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;1&lt;/strong&gt;, N = 112&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>1</strong>, N = 112<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Tumor Response</td>
<td headers="stat_1" class="gt_row gt_center"><br /></td>
<td headers="stat_2" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    0</td>
<td headers="stat_1" class="gt_row gt_center">49 (57%)</td>
<td headers="stat_2" class="gt_row gt_center">83 (78%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    1</td>
<td headers="stat_1" class="gt_row gt_center">37 (43%)</td>
<td headers="stat_2" class="gt_row gt_center">24 (22%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_1" class="gt_row gt_center">2</td>
<td headers="stat_2" class="gt_row gt_center">5</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> n (%)</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
<div id="skim-function" class="section level4 hasAnchor" number="1.2.5.7">
<h4><span class="header-section-number">1.2.5.7</span> <code>skim</code> function<a href="week-1.html#skim-function" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>skim</code> function (from the {skimr} package) gives basic summary data.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="week-1.html#cb38-1" tabindex="-1"></a><span class="co"># Show summary statistics for &quot;age&quot;</span></span>
<span id="cb38-2"><a href="week-1.html#cb38-2" tabindex="-1"></a><span class="fu">skim</span>(lesson1a<span class="sc">$</span>age)</span></code></pre></div>
<table>
<caption><span id="tab:section1i">Table 1.3: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">lesson1a$age</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">386</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="18%" />
<col width="13%" />
<col width="18%" />
<col width="7%" />
<col width="7%" />
<col width="3%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="6%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">data</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">49.48</td>
<td align="right">13.75</td>
<td align="right">19</td>
<td align="right">40</td>
<td align="right">49</td>
<td align="right">59</td>
<td align="right">86</td>
<td align="left">▃▇▇▅▁</td>
</tr>
</tbody>
</table>
<p>So of the 386 patients, there are no patients who are missing the “age” variable (the “n_missing” column = 0), the mean age (a type of average, I’ll explain next week) is 49.48 (column “mean”), the standard deviation (again, I’ll explain next week) is 13.75 (column “sd”). The youngest patient was 19 (column “p0”) and the oldest is 86 (column “p100”).</p>
<p>This simple command gives us our first lesson about the dangers of statistical software: it gives the age to within a few days. So if you were reporting results for a journal, you would never say that mean age was 49.48, you’d probably just say 49.</p>
<p>“p0” here represents the minimum age in the dataset - 19. “p100” represents the maximum age of 86. “p25”, “p50” and “p75” are the centiles. We’ll talk more about this later, but briefly, “p25 = 40” means that 25% of the patients were aged 40 and younger. The number by “p50” (i.e. 49) is the median.</p>
</div>
<div id="mutate-function" class="section level4 hasAnchor" number="1.2.5.8">
<h4><span class="header-section-number">1.2.5.8</span> <code>mutate</code> function<a href="week-1.html#mutate-function" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>mutate</code> function is used to create new variables, or replace variable values.</p>
<p>The code below means: create a new variable called “a” and set it equal to 1 in all observations. The “&lt;-” indicator means to then save out this new dataset including the “a” variable as <strong>lesson1a</strong>, replacing the old <strong>lesson1a</strong> dataset that does not include “a”.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="week-1.html#cb39-1" tabindex="-1"></a><span class="co"># Save the data out as &quot;lesson1a&quot;</span></span>
<span id="cb39-2"><a href="week-1.html#cb39-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb39-3"><a href="week-1.html#cb39-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span> <span class="co"># Take the current &quot;lesson1a&quot; dataset</span></span>
<span id="cb39-4"><a href="week-1.html#cb39-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> <span class="dv">1</span>) <span class="co"># And add a variable called &quot;a&quot; with a value of &quot;1&quot;</span></span></code></pre></div>
<p>Since we have already created the variable “a” above, the code below means: replace the variable “a” with the value of 2 in all observations.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="week-1.html#cb40-1" tabindex="-1"></a><span class="co"># Replace the value of &quot;a&quot; with &quot;2&quot; for all observations</span></span>
<span id="cb40-2"><a href="week-1.html#cb40-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb40-3"><a href="week-1.html#cb40-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="week-1.html#cb40-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> <span class="dv">2</span>)</span></code></pre></div>
<p>You can also replace one variable with the value of another variable. The code below means: replace the variable “a” with whatever the value of “p1” is in each observation.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="week-1.html#cb41-1" tabindex="-1"></a><span class="co"># Replace the value of &quot;a&quot; with the value of &quot;p1&quot; for all observations</span></span>
<span id="cb41-2"><a href="week-1.html#cb41-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb41-3"><a href="week-1.html#cb41-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="week-1.html#cb41-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> p1)</span></code></pre></div>
<p>You can also calculate values inside a <code>mutate</code> statement. For example, you can create an average of the four variables “p1” - “p4”.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="week-1.html#cb42-1" tabindex="-1"></a><span class="co"># Replace &quot;a&quot; with the average of &quot;p1&quot;, &quot;p2&quot;, &quot;p3&quot; and &quot;p4&quot;</span></span>
<span id="cb42-2"><a href="week-1.html#cb42-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb42-3"><a href="week-1.html#cb42-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="week-1.html#cb42-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> (p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3 <span class="sc">+</span> p4)<span class="sc">/</span><span class="dv">4</span>)</span></code></pre></div>
</div>
<div id="if_else-function" class="section level4 hasAnchor" number="1.2.5.9">
<h4><span class="header-section-number">1.2.5.9</span> <code>if_else</code> function<a href="week-1.html#if_else-function" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>if_else</code> function can be used with the <code>mutate</code> function to assign values to a variable based on a specific condition.</p>
<p>The first argument in the <code>if_else</code> function is the “if” condition. The second argument is the value of the variable for observations that meet the “if” condition. The third argument is the value of the variable for observations that do not meet the “if” condition.</p>
<p>For example, the code below says: replace the value of “a” with “p1” if “p1” is greater than 4. Otherwise, keep the original value “a”.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="week-1.html#cb43-1" tabindex="-1"></a><span class="co"># Replace the value of &quot;a&quot; with &quot;p1&quot; if the value of &quot;p1&quot; is greater than 4</span></span>
<span id="cb43-2"><a href="week-1.html#cb43-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb43-3"><a href="week-1.html#cb43-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="week-1.html#cb43-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> <span class="fu">if_else</span>(p1 <span class="sc">&gt;</span> <span class="dv">4</span>, p1, a))</span></code></pre></div>
<p>In this case, we are only replacing for females. Note that when you use an equal sign after an “if” statement you have to use two of them in a row to signify “is equal to” (==) rather than “make equal to” (=).</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="week-1.html#cb44-1" tabindex="-1"></a><span class="co"># Replace the value of &quot;a&quot; with &quot;p1&quot; if &quot;sex&quot; equals 1 (female)</span></span>
<span id="cb44-2"><a href="week-1.html#cb44-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb44-3"><a href="week-1.html#cb44-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="week-1.html#cb44-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> <span class="fu">if_else</span>(sex <span class="sc">==</span> <span class="dv">1</span>, p1, a))</span></code></pre></div>
<p>The <code>|</code> sign means “or”, such that the code below means: set “a” equal to 1 if “y” is equal to either “campus” or “peds”. Otherwise, keep the original value of “a”.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="week-1.html#cb45-1" tabindex="-1"></a><span class="co"># Replace the value of &quot;a&quot; with &quot;1&quot; if &quot;y&quot; is equal to either &quot;campus&quot; or &quot;peds&quot;</span></span>
<span id="cb45-2"><a href="week-1.html#cb45-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb45-3"><a href="week-1.html#cb45-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="week-1.html#cb45-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> <span class="fu">if_else</span>(y <span class="sc">==</span> <span class="st">&quot;campus&quot;</span> <span class="sc">|</span> y <span class="sc">==</span> <span class="st">&quot;peds&quot;</span>, <span class="dv">1</span>, a))</span></code></pre></div>
<p>You can give check for more than one condition by using the <code>&amp;</code> sign. This code looks for observations where the patient is female (sex == 1) and the patient is older than 50 (age &gt; 50). This creates a subgroup of older women: “a” is 1 for older women and 0 for everybody else.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="week-1.html#cb46-1" tabindex="-1"></a><span class="co"># Replace the value of &quot;a&quot; with 1 if sex equals 1 (female) and age &gt; 50</span></span>
<span id="cb46-2"><a href="week-1.html#cb46-2" tabindex="-1"></a><span class="co"># For all other observations, replace &quot;a&quot; with 0</span></span>
<span id="cb46-3"><a href="week-1.html#cb46-3" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb46-4"><a href="week-1.html#cb46-4" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="week-1.html#cb46-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> <span class="fu">if_else</span>(sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> age <span class="sc">&gt;</span> <span class="dv">50</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code></pre></div>
</div>
<div id="renaming-and-labeling-variables" class="section level4 hasAnchor" number="1.2.5.10">
<h4><span class="header-section-number">1.2.5.10</span> Renaming and Labeling Variables<a href="week-1.html#renaming-and-labeling-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To rename a variable, you can use the <code>rename</code> function. We have to make sure that the new variable name overwrites the old variable name, so we have to use the assignment operator (<code>&lt;-</code>).</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="week-1.html#cb47-1" tabindex="-1"></a><span class="co"># Rename variable y</span></span>
<span id="cb47-2"><a href="week-1.html#cb47-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span></span>
<span id="cb47-3"><a href="week-1.html#cb47-3" tabindex="-1"></a>  lesson1a <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="week-1.html#cb47-4" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">location =</span> y)</span></code></pre></div>
<p>To label a variable, use <code>attr</code>. This automatically overwrites the old label.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="week-1.html#cb48-1" tabindex="-1"></a><span class="co"># Print the variable with the old label</span></span>
<span id="cb48-2"><a href="week-1.html#cb48-2" tabindex="-1"></a><span class="fu">str</span>(trial<span class="sc">$</span>response)</span></code></pre></div>
<pre><code>##  int [1:200] 0 1 0 1 1 0 0 0 0 0 ...
##  - attr(*, &quot;label&quot;)= chr &quot;Tumor Response&quot;</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="week-1.html#cb50-1" tabindex="-1"></a><span class="co"># Label the response variable</span></span>
<span id="cb50-2"><a href="week-1.html#cb50-2" tabindex="-1"></a><span class="fu">attr</span>(trial<span class="sc">$</span>response, <span class="st">&quot;label&quot;</span>) <span class="ot">&lt;-</span> <span class="st">&quot;0: No Tumor Response, 1: Tumor Response&quot;</span></span>
<span id="cb50-3"><a href="week-1.html#cb50-3" tabindex="-1"></a></span>
<span id="cb50-4"><a href="week-1.html#cb50-4" tabindex="-1"></a><span class="co"># Confirm new label is correct</span></span>
<span id="cb50-5"><a href="week-1.html#cb50-5" tabindex="-1"></a><span class="fu">str</span>(trial<span class="sc">$</span>response)</span></code></pre></div>
<pre><code>##  int [1:200] 0 1 0 1 1 0 0 0 0 0 ...
##  - attr(*, &quot;label&quot;)= chr &quot;0: No Tumor Response, 1: Tumor Response&quot;</code></pre>
</div>
</div>
<div id="using-help" class="section level3 hasAnchor" number="1.2.6">
<h3><span class="header-section-number">1.2.6</span> Using Help<a href="week-1.html#using-help" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The help feature in R can be useful if you know the name of the function that you need assistance with. Sometimes, the help file for a function can be very technical at the top, but if you scroll to the bottom, there is an “examples” section which will show different examples of the code. You can copy and paste these examples and run them on your own machine which can help you better understand how to use the functions. To access the help file for a function, you can type <code>?functionname</code> (e.g., <code>?skim</code>) or <code>?packagename::functionname</code> if you have not loaded the package using the <code>library</code> command.</p>
<p>Unfortunately, the R help function is not very useful if you don’t know the function you are trying to use. However, there are some websites that can be useful to learn more about the common functions used in the course.</p>
<div id="data-manipulation" class="section level4 hasAnchor" number="1.2.6.1">
<h4><span class="header-section-number">1.2.6.1</span> Data Manipulation<a href="week-1.html#data-manipulation" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Most of the data manipulation we will be doing in this course, such as creating variables and selecting specific variables and observations to keep, is done using functions from the {dplyr} package (part of the {tidyverse} package). This includes the <code>select</code> and <code>mutate</code> functions that you’ve seen in this lesson, as well as other functions you will see in future lessons, like <code>filter</code>. Click <a href="https://dplyr.tidyverse.org/">here</a> if you need help remembering which function to use, or need code examples for these functions.</p>
</div>
<div id="statistical-functions" class="section level4 hasAnchor" number="1.2.6.2">
<h4><span class="header-section-number">1.2.6.2</span> Statistical Functions<a href="week-1.html#statistical-functions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Most of the statistical functions that will be used in this course are included in the {stats} package, which is pre-loaded when you install R. These include the following functions, among others: <code>quantile</code>, <code>binom.test</code>, <code>t.test</code>, <code>wilcox.test</code>, <code>fisher.test</code>, <code>lm</code> and <code>glm</code>. You can access the help files for these using the <code>?functionname</code> notation, for example, <code>?quantile</code>.</p>
<p>If you need help deciding which statistical functions to use, the best place to start would be searching through the statistics course online book, using the magnifying glass option at the top left. For example, if you search “logistic regression”, you can find section 5.2.4 “Logistic regression”, which will take you to the section of the course on this topic.</p>
</div>
<div id="tables" class="section level4 hasAnchor" number="1.2.6.3">
<h4><span class="header-section-number">1.2.6.3</span> Tables<a href="week-1.html#tables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For more information on the {gtsummary} package, which creates formatted tables, click <a href="http://www.danieldsjoberg.com/gtsummary/">here</a>.</p>
</div>
</div>
</div>
<div id="assignments" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Assignments<a href="week-1.html#assignments" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="week-1.html#cb52-1" tabindex="-1"></a><span class="co"># Copy and paste this code to load the data for week 1 assignments</span></span>
<span id="cb52-2"><a href="week-1.html#cb52-2" tabindex="-1"></a>lesson1a <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;Week 1&quot;</span>, <span class="st">&quot;lesson1a.rds&quot;</span>))</span></code></pre></div>
<p>The data for you to look at are in the attached file <code>lesson1a.rds</code>.</p>
<p>This is data for 386 patients undergoing surgery. What type of data (e.g. continuous, binary, ordinal, nonsense) are each of the variables?</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://www.github.com/emilyvertosick/Statistics-Course/edit/master/01-week1.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
