<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Week 6 Week 5 | MSKCC Biostatistics Course</title>
  <meta name="description" content="Statistics Course" />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Week 6 Week 5 | MSKCC Biostatistics Course" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Statistics Course" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 6 Week 5 | MSKCC Biostatistics Course" />
  
  <meta name="twitter:description" content="Statistics Course" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-4.html">
<link rel="next" href="week-6.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>General Course Materials</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-outline"><i class="fa fa-check"></i>Course Outline</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#andrews-contact-details"><i class="fa fa-check"></i>Andrew’s Contact Details</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#passing-the-course"><i class="fa fa-check"></i>Passing the Course</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#data-checking-procedures"><i class="fa fa-check"></i>Data Checking Procedures</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#guidelines-for-presentation-of-statistics"><i class="fa fa-check"></i>Guidelines for presentation of statistics</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#r-instructions"><i class="fa fa-check"></i><b>1.1</b> R Instructions</a><ul>
<li class="chapter" data-level="1.1.1" data-path="getting-started.html"><a href="getting-started.html#using-rstudio"><i class="fa fa-check"></i><b>1.1.1</b> Using RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path="getting-started.html"><a href="getting-started.html#setting-up-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> Setting Up RStudio</a></li>
<li class="chapter" data-level="1.1.3" data-path="getting-started.html"><a href="getting-started.html#opening-a-data-file-created-by-someone-else"><i class="fa fa-check"></i><b>1.1.3</b> Opening a data file created by someone else</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#looking-at-the-data"><i class="fa fa-check"></i><b>1.2</b> Looking at the data</a><ul>
<li class="chapter" data-level="1.2.1" data-path="getting-started.html"><a href="getting-started.html#typing-a-command"><i class="fa fa-check"></i><b>1.2.1</b> Typing a command</a></li>
<li class="chapter" data-level="1.2.2" data-path="getting-started.html"><a href="getting-started.html#some-useful-commands"><i class="fa fa-check"></i><b>1.2.2</b> Some Useful Commands</a></li>
<li class="chapter" data-level="1.2.3" data-path="getting-started.html"><a href="getting-started.html#using-help"><i class="fa fa-check"></i><b>1.2.3</b> Using Help</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="todo-discuss-with-andrew-re-taking-this-section-out.html"><a href="todo-discuss-with-andrew-re-taking-this-section-out.html"><i class="fa fa-check"></i><b>2</b> TODO: Discuss with Andrew re: taking this section out</a><ul>
<li class="chapter" data-level="2.1" data-path="todo-discuss-with-andrew-re-taking-this-section-out.html"><a href="todo-discuss-with-andrew-re-taking-this-section-out.html#assignments"><i class="fa fa-check"></i><b>2.1</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>3</b> Week 2</a><ul>
<li class="chapter" data-level="3.1" data-path="week-2.html"><a href="week-2.html#r-instructions-1"><i class="fa fa-check"></i><b>3.1</b> R Instructions</a><ul>
<li class="chapter" data-level="3.1.1" data-path="week-2.html"><a href="week-2.html#summarizing-continuous-variables"><i class="fa fa-check"></i><b>3.1.1</b> Summarizing continuous variables</a></li>
<li class="chapter" data-level="3.1.2" data-path="week-2.html"><a href="week-2.html#centiles"><i class="fa fa-check"></i><b>3.1.2</b> Centiles</a></li>
<li class="chapter" data-level="3.1.3" data-path="week-2.html"><a href="week-2.html#one-way-tables"><i class="fa fa-check"></i><b>3.1.3</b> One-way tables</a></li>
<li class="chapter" data-level="3.1.4" data-path="week-2.html"><a href="week-2.html#two-way-tables"><i class="fa fa-check"></i><b>3.1.4</b> Two-way tables</a></li>
<li class="chapter" data-level="3.1.5" data-path="week-2.html"><a href="week-2.html#graphing"><i class="fa fa-check"></i><b>3.1.5</b> Graphing</a></li>
<li class="chapter" data-level="3.1.6" data-path="week-2.html"><a href="week-2.html#further-reading"><i class="fa fa-check"></i><b>3.1.6</b> Further Reading</a></li>
<li class="chapter" data-level="3.1.7" data-path="week-2.html"><a href="week-2.html#using-r-as-a-calculator"><i class="fa fa-check"></i><b>3.1.7</b> Using R as a calculator</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="week-2.html"><a href="week-2.html#assignment"><i class="fa fa-check"></i><b>3.2</b> Assignment</a><ul>
<li class="chapter" data-level="3.2.1" data-path="week-2.html"><a href="week-2.html#assignments-1"><i class="fa fa-check"></i><b>3.2.1</b> Assignments</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i><b>4</b> Week 3</a><ul>
<li class="chapter" data-level="4.1" data-path="week-3.html"><a href="week-3.html#r-instructions-2"><i class="fa fa-check"></i><b>4.1</b> R Instructions</a></li>
<li class="chapter" data-level="4.2" data-path="week-3.html"><a href="week-3.html#hypothesis-testing"><i class="fa fa-check"></i><b>4.2</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="4.2.1" data-path="week-3.html"><a href="week-3.html#t-test"><i class="fa fa-check"></i><b>4.2.1</b> <strong>t-test</strong></a></li>
<li class="chapter" data-level="4.2.2" data-path="week-3.html"><a href="week-3.html#non-parametric-methods"><i class="fa fa-check"></i><b>4.2.2</b> <strong>Non-parametric methods</strong></a></li>
<li class="chapter" data-level="4.2.3" data-path="week-3.html"><a href="week-3.html#the-binomial-test"><i class="fa fa-check"></i><b>4.2.3</b> <strong>The binomial test</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="week-3.html"><a href="week-3.html#assignments-2"><i class="fa fa-check"></i><b>4.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>5</b> Week 4</a><ul>
<li class="chapter" data-level="5.1" data-path="week-4.html"><a href="week-4.html#r-instructions-3"><i class="fa fa-check"></i><b>5.1</b> R Instructions</a></li>
<li class="chapter" data-level="5.2" data-path="week-4.html"><a href="week-4.html#tables"><i class="fa fa-check"></i><b>5.2</b> Tables</a></li>
<li class="chapter" data-level="5.3" data-path="week-4.html"><a href="week-4.html#getting-estimates-risk-difference-risk-ratio-odds-ratio"><i class="fa fa-check"></i><b>5.3</b> Getting estimates: risk difference, risk ratio, odds ratio</a></li>
<li class="chapter" data-level="5.4" data-path="week-4.html"><a href="week-4.html#assignments-3"><i class="fa fa-check"></i><b>5.4</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>6</b> Week 5</a><ul>
<li class="chapter" data-level="6.1" data-path="week-5.html"><a href="week-5.html#r-instructions-4"><i class="fa fa-check"></i><b>6.1</b> R Instructions</a></li>
<li class="chapter" data-level="6.2" data-path="week-5.html"><a href="week-5.html#correlation"><i class="fa fa-check"></i><b>6.2</b> Correlation</a></li>
<li class="chapter" data-level="6.3" data-path="week-5.html"><a href="week-5.html#linear-regression"><i class="fa fa-check"></i><b>6.3</b> Linear regression</a></li>
<li class="chapter" data-level="6.4" data-path="week-5.html"><a href="week-5.html#graphing-the-data"><i class="fa fa-check"></i><b>6.4</b> Graphing the data</a></li>
<li class="chapter" data-level="6.5" data-path="week-5.html"><a href="week-5.html#logistic-regression"><i class="fa fa-check"></i><b>6.5</b> Logistic regression</a></li>
<li class="chapter" data-level="6.6" data-path="week-5.html"><a href="week-5.html#getting-the-area-under-the-curve"><i class="fa fa-check"></i><b>6.6</b> Getting the area-under-the-curve</a></li>
<li class="chapter" data-level="6.7" data-path="week-5.html"><a href="week-5.html#assignments-4"><i class="fa fa-check"></i><b>6.7</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>7</b> Week 6</a><ul>
<li class="chapter" data-level="7.1" data-path="week-6.html"><a href="week-6.html#r-instructions-5"><i class="fa fa-check"></i><b>7.1</b> R Instructions</a></li>
<li class="chapter" data-level="7.2" data-path="week-6.html"><a href="week-6.html#diagnostic-tests"><i class="fa fa-check"></i><b>7.2</b> Diagnostic Tests</a></li>
<li class="chapter" data-level="7.3" data-path="week-6.html"><a href="week-6.html#assignments-5"><i class="fa fa-check"></i><b>7.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>8</b> Week 7</a><ul>
<li class="chapter" data-level="8.1" data-path="week-7.html"><a href="week-7.html#r-instructions-6"><i class="fa fa-check"></i><b>8.1</b> R Instructions</a></li>
<li class="chapter" data-level="8.2" data-path="week-7.html"><a href="week-7.html#time-to-event-data"><i class="fa fa-check"></i><b>8.2</b> Time to event data</a></li>
<li class="chapter" data-level="8.3" data-path="week-7.html"><a href="week-7.html#assignments-6"><i class="fa fa-check"></i><b>8.3</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-8.html"><a href="week-8.html"><i class="fa fa-check"></i><b>9</b> Week 8</a></li>
<li class="chapter" data-level="10" data-path="assignment-answers.html"><a href="assignment-answers.html"><i class="fa fa-check"></i><b>10</b> Assignment Answers</a><ul>
<li class="chapter" data-level="10.1" data-path="assignment-answers.html"><a href="assignment-answers.html#week-1"><i class="fa fa-check"></i><b>10.1</b> Week 1</a></li>
<li class="chapter" data-level="10.2" data-path="assignment-answers.html"><a href="assignment-answers.html#week-2-1"><i class="fa fa-check"></i><b>10.2</b> Week 2</a><ul>
<li class="chapter" data-level="10.2.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2a.rds"><i class="fa fa-check"></i><b>10.2.1</b> lesson2a.rds</a></li>
<li class="chapter" data-level="10.2.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2b.rds"><i class="fa fa-check"></i><b>10.2.2</b> lesson2b.rds</a></li>
<li class="chapter" data-level="10.2.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2c.rds"><i class="fa fa-check"></i><b>10.2.3</b> lesson2c.rds</a></li>
<li class="chapter" data-level="10.2.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2d.rds"><i class="fa fa-check"></i><b>10.2.4</b> lesson2d.rds</a></li>
<li class="chapter" data-level="10.2.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson2e.rds-cancer-pain"><i class="fa fa-check"></i><b>10.2.5</b> lesson2e.rds: Cancer pain</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="assignment-answers.html"><a href="assignment-answers.html#week-3-1"><i class="fa fa-check"></i><b>10.3</b> Week 3</a><ul>
<li class="chapter" data-level="10.3.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3a.rds"><i class="fa fa-check"></i><b>10.3.1</b> lesson3a.rds</a></li>
<li class="chapter" data-level="10.3.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3b.rds"><i class="fa fa-check"></i><b>10.3.2</b> lesson3b.rds</a></li>
<li class="chapter" data-level="10.3.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3c.rds"><i class="fa fa-check"></i><b>10.3.3</b> lesson3c.rds</a></li>
<li class="chapter" data-level="10.3.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3d.rds"><i class="fa fa-check"></i><b>10.3.4</b> lesson3d.rds</a></li>
<li class="chapter" data-level="10.3.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3e.rds"><i class="fa fa-check"></i><b>10.3.5</b> lesson3e.rds</a></li>
<li class="chapter" data-level="10.3.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson3f.rds"><i class="fa fa-check"></i><b>10.3.6</b> lesson3f.rds</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="assignment-answers.html"><a href="assignment-answers.html#week-4-1"><i class="fa fa-check"></i><b>10.4</b> Week 4</a><ul>
<li class="chapter" data-level="10.4.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4a.rds"><i class="fa fa-check"></i><b>10.4.1</b> lesson4a.rds</a></li>
<li class="chapter" data-level="10.4.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4b.rds"><i class="fa fa-check"></i><b>10.4.2</b> lesson4b.rds</a></li>
<li class="chapter" data-level="10.4.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4c.rds"><i class="fa fa-check"></i><b>10.4.3</b> lesson4c.rds</a></li>
<li class="chapter" data-level="10.4.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4d.rds"><i class="fa fa-check"></i><b>10.4.4</b> lesson4d.rds</a></li>
<li class="chapter" data-level="10.4.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson4e.rds"><i class="fa fa-check"></i><b>10.4.5</b> lesson4e.rds</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="assignment-answers.html"><a href="assignment-answers.html#week-5-1"><i class="fa fa-check"></i><b>10.5</b> Week 5</a><ul>
<li class="chapter" data-level="10.5.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5a.rds"><i class="fa fa-check"></i><b>10.5.1</b> lesson5a.rds</a></li>
<li class="chapter" data-level="10.5.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5b.rds"><i class="fa fa-check"></i><b>10.5.2</b> lesson5b.rds</a></li>
<li class="chapter" data-level="10.5.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5c.rds"><i class="fa fa-check"></i><b>10.5.3</b> lesson5c.rds</a></li>
<li class="chapter" data-level="10.5.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5d.rds"><i class="fa fa-check"></i><b>10.5.4</b> lesson5d.rds</a></li>
<li class="chapter" data-level="10.5.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5e.rds"><i class="fa fa-check"></i><b>10.5.5</b> lesson5e.rds</a></li>
<li class="chapter" data-level="10.5.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5f.rds"><i class="fa fa-check"></i><b>10.5.6</b> lesson5f.rds</a></li>
<li class="chapter" data-level="10.5.7" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5g.rds"><i class="fa fa-check"></i><b>10.5.7</b> lesson5g.rds</a></li>
<li class="chapter" data-level="10.5.8" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5h.rds"><i class="fa fa-check"></i><b>10.5.8</b> lesson5h.rds</a></li>
<li class="chapter" data-level="10.5.9" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson5i.rds"><i class="fa fa-check"></i><b>10.5.9</b> lesson5i.rds</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="assignment-answers.html"><a href="assignment-answers.html#week-6-1"><i class="fa fa-check"></i><b>10.6</b> Week 6</a><ul>
<li class="chapter" data-level="10.6.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6a.rds-and-lesson6b.rds"><i class="fa fa-check"></i><b>10.6.1</b> lesson6a.rds and lesson6b.rds</a></li>
<li class="chapter" data-level="10.6.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6c.rds"><i class="fa fa-check"></i><b>10.6.2</b> lesson6c.rds</a></li>
<li class="chapter" data-level="10.6.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6d.rds"><i class="fa fa-check"></i><b>10.6.3</b> lesson6d.rds</a></li>
<li class="chapter" data-level="10.6.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6e"><i class="fa fa-check"></i><b>10.6.4</b> lesson6e</a></li>
<li class="chapter" data-level="10.6.5" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6f"><i class="fa fa-check"></i><b>10.6.5</b> lesson6f</a></li>
<li class="chapter" data-level="10.6.6" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson6g"><i class="fa fa-check"></i><b>10.6.6</b> lesson6g</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="assignment-answers.html"><a href="assignment-answers.html#week-7-1"><i class="fa fa-check"></i><b>10.7</b> Week 7</a><ul>
<li class="chapter" data-level="10.7.1" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7a.rds"><i class="fa fa-check"></i><b>10.7.1</b> lesson7a.rds</a></li>
<li class="chapter" data-level="10.7.2" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7b.rds"><i class="fa fa-check"></i><b>10.7.2</b> lesson7b.rds</a></li>
<li class="chapter" data-level="10.7.3" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7c.rds"><i class="fa fa-check"></i><b>10.7.3</b> lesson7c.rds</a></li>
<li class="chapter" data-level="10.7.4" data-path="assignment-answers.html"><a href="assignment-answers.html#lesson7d.rds"><i class="fa fa-check"></i><b>10.7.4</b> lesson7d.rds</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="exam.html"><a href="exam.html"><i class="fa fa-check"></i><b>11</b> Exam</a><ul>
<li class="chapter" data-level="11.1" data-path="exam.html"><a href="exam.html#question-1"><i class="fa fa-check"></i><b>11.1</b> Question 1</a></li>
<li class="chapter" data-level="11.2" data-path="exam.html"><a href="exam.html#question-2"><i class="fa fa-check"></i><b>11.2</b> Question 2</a></li>
<li class="chapter" data-level="11.3" data-path="exam.html"><a href="exam.html#question-3"><i class="fa fa-check"></i><b>11.3</b> Question 3</a></li>
<li class="chapter" data-level="11.4" data-path="exam.html"><a href="exam.html#question-4"><i class="fa fa-check"></i><b>11.4</b> Question 4</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MSKCC Biostatistics Course</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-5" class="section level1">
<h1><span class="header-section-number">Week 6</span> Week 5</h1>
<div id="r-instructions-4" class="section level2">
<h2><span class="header-section-number">6.1</span> R Instructions</h2>
<p>For this lesson, make sure you have loaded the following packages.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1"><span class="kw">library</span>(skimr)</a>
<a class="sourceLine" id="cb124-2" title="2"><span class="kw">library</span>(gtsummary)</a>
<a class="sourceLine" id="cb124-3" title="3"><span class="kw">library</span>(epiR)</a>
<a class="sourceLine" id="cb124-4" title="4"><span class="kw">library</span>(broom)</a>
<a class="sourceLine" id="cb124-5" title="5"><span class="kw">library</span>(pROC)</a>
<a class="sourceLine" id="cb124-6" title="6"><span class="kw">library</span>(gmodels)</a>
<a class="sourceLine" id="cb124-7" title="7"><span class="kw">library</span>(survival)</a>
<a class="sourceLine" id="cb124-8" title="8"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
</div>
<div id="correlation" class="section level2">
<h2><span class="header-section-number">6.2</span> Correlation</h2>
<p>Correlating two or more variables is very easy: just use the <code>cor</code> function and then the dataset and selected variables.</p>
<p>For example, if you use the “lesson2b.rds” dataset and correlate the first four pain scores, you get the following table:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" title="1"><span class="kw">cor</span>(lesson2b <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(l01, l02, l03, l04))</a></code></pre></div>
<pre><code>##           l01       l02       l03       l04
## l01 1.0000000 0.7900984 0.6270860 0.5395075
## l02 0.7900984 1.0000000 0.8145025 0.7148299
## l03 0.6270860 0.8145025 1.0000000 0.8383224
## l04 0.5395075 0.7148299 0.8383224 1.0000000</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" title="1"><span class="co"># The &quot;select&quot; function allows you to keep specific columns from your dataset</span></a></code></pre></div>
<p>This shows, for example, that the correlation between l01 and l02 is 0.79 and the correlation between l02 and l04 is 0.71. From the table you can easily see that pain scores taken on consecutive days are more strongly correlated than those taken two or three days apart.</p>
<p>If the data are skewed, you can try a regression based on ranks, what is known as Spearman’s rank correlation. What you’d type is the same as above, but adding the option <code>method = "spearman"</code>.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1"><span class="kw">cor</span>(lesson2b <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(l01, l02, l03, l04), <span class="dt">method =</span> <span class="st">&quot;spearman&quot;</span>)</a></code></pre></div>
<pre><code>##           l01       l02       l03       l04
## l01 1.0000000 0.7799856 0.6220233 0.5443327
## l02 0.7799856 1.0000000 0.8126008 0.7220277
## l03 0.6220233 0.8126008 1.0000000 0.8324906
## l04 0.5443327 0.7220277 0.8324906 1.0000000</code></pre>
</div>
<div id="linear-regression" class="section level2">
<h2><span class="header-section-number">6.3</span> Linear regression</h2>
<p>Linear regression is when you try to predict a continuous variable. The function to use is <code>lm</code>.</p>
<p>The first variable is the dependent variable (e.g. blood pressure) and must be continuous. The other variables are the predictor variables and can be binary or continuous: in some cases you can use ordinal variables but you have to be careful. We’ll deal with categorical variables later in the course. The dependent and predictor variables are separated by a “~”, and multiple predictor variables are separated by “+”.</p>
<p>Let’s use the data from “lesson3d.rds” as an example dataset. We want to see if we can predict a patient’s range of motion after treatment (variable a) in terms of their age, sex and pre-treatment range of motion (variable b).</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1"><span class="kw">lm</span>(a <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>b, <span class="dt">data =</span> lesson3d)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = a ~ sex + age + b, data = lesson3d)
## 
## Coefficients:
## (Intercept)          sex          age            b  
##    138.7336       2.8524      -0.4359       0.6692</code></pre>
<p>This gives you the very basic information from the regression, but you can get more information using the <code>summary</code> function:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1">rom_model &lt;-<span class="st"> </span><span class="kw">lm</span>(a <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>b, <span class="dt">data =</span> lesson3d)</a>
<a class="sourceLine" id="cb132-2" title="2"><span class="kw">summary</span>(rom_model)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = a ~ sex + age + b, data = lesson3d)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -60.135 -11.943   3.238  14.523  47.732 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 138.73363   29.50514   4.702 5.40e-05 ***
## sex           2.85241   10.25817   0.278    0.783    
## age          -0.43589    0.27770  -1.570    0.127    
## b             0.66924    0.07816   8.563 1.49e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 25.29 on 30 degrees of freedom
## Multiple R-squared:  0.7475, Adjusted R-squared:  0.7222 
## F-statistic:  29.6 on 3 and 30 DF,  p-value: 4.241e-09</code></pre>
<p>The first column of numbers listed under “Coefficients” are the coefficients. You can interpret this as follows: start with 138.7 degrees of range of motion (the intercept or constant). Then add 2.85 if the patient is a woman, and take away 0.436 degrees for every year of age. Find, add 0.669 degrees for every degree of range of motion the patient had before the trial.</p>
<p>Let’s take a single patient: a 54 year old woman with a range of motion of 301 before treatment. Her predicted range of motion afterwards is 138.7 + 2.85 - 0.436*54 + 0.669*301 = 319.5. Her actual figure was 325, so we predicted quite well for this patient. You can get R to do this automatically using the <code>augment</code> function from the <code>broom</code> package.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1"><span class="co"># The &quot;augment&quot; function creates a dataset of all patients included in the model</span></a>
<a class="sourceLine" id="cb134-2" title="2"><span class="co"># and all variables included in the model, as well as the predictions</span></a>
<a class="sourceLine" id="cb134-3" title="3"><span class="co"># The &quot;.fitted&quot; column is your prediction</span></a>
<a class="sourceLine" id="cb134-4" title="4"></a>
<a class="sourceLine" id="cb134-5" title="5">lesson3d_pred &lt;-</a>
<a class="sourceLine" id="cb134-6" title="6"><span class="st">  </span><span class="kw">augment</span>(rom_model,</a>
<a class="sourceLine" id="cb134-7" title="7">          <span class="dt">newdata =</span> lesson3d)</a></code></pre></div>
<p>To get the number of observations, coefficients, 95% confidence interval and p-values printed in a table for all covariates, you can use the <code>tbl_regression</code> function from the <code>gtsummary</code> package:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" title="1"><span class="kw">tbl_regression</span>(rom_model)</a></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#iwrgxmosvm .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #000000;
  font-size: 16px;
  background-color: #FFFFFF;
  /* table.background.color */
  width: auto;
  /* table.width */
  border-top-style: solid;
  /* table.border.top.style */
  border-top-width: 2px;
  /* table.border.top.width */
  border-top-color: #A8A8A8;
  /* table.border.top.color */
  border-bottom-style: solid;
  /* table.border.bottom.style */
  border-bottom-width: 2px;
  /* table.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* table.border.bottom.color */
}

#iwrgxmosvm .gt_heading {
  background-color: #FFFFFF;
  /* heading.background.color */
  border-bottom-color: #FFFFFF;
}

#iwrgxmosvm .gt_title {
  color: #000000;
  font-size: 125%;
  /* heading.title.font.size */
  padding-top: 4px;
  /* heading.top.padding */
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#iwrgxmosvm .gt_subtitle {
  color: #000000;
  font-size: 85%;
  /* heading.subtitle.font.size */
  padding-top: 2px;
  padding-bottom: 2px;
  /* heading.bottom.padding */
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#iwrgxmosvm .gt_bottom_border {
  border-bottom-style: solid;
  /* heading.border.bottom.style */
  border-bottom-width: 2px;
  /* heading.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* heading.border.bottom.color */
}

#iwrgxmosvm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  padding-top: 4px;
  padding-bottom: 4px;
}

#iwrgxmosvm .gt_col_heading {
  color: #000000;
  background-color: #FFFFFF;
  /* column_labels.background.color */
  font-size: 16px;
  /* column_labels.font.size */
  font-weight: initial;
  /* column_labels.font.weight */
  vertical-align: middle;
  padding: 10px;
  margin: 10px;
}

#iwrgxmosvm .gt_columns_top_border {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#iwrgxmosvm .gt_columns_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#iwrgxmosvm .gt_sep_right {
  border-right: 5px solid #FFFFFF;
}

#iwrgxmosvm .gt_group_heading {
  padding: 8px;
  color: #000000;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #A8A8A8;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#iwrgxmosvm .gt_empty_group_heading {
  padding: 0.5px;
  color: #000000;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #A8A8A8;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#iwrgxmosvm .gt_striped {
  background-color: #f2f2f2;
}

#iwrgxmosvm .gt_from_md > :first-child {
  margin-top: 0;
}

#iwrgxmosvm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#iwrgxmosvm .gt_row {
  padding: 8px;
  /* row.padding */
  margin: 10px;
  vertical-align: middle;
}

#iwrgxmosvm .gt_stub {
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #A8A8A8;
  padding-left: 12px;
}

#iwrgxmosvm .gt_summary_row {
  color: #000000;
  background-color: #FFFFFF;
  /* summary_row.background.color */
  padding: 8px;
  /* summary_row.padding */
  text-transform: inherit;
  /* summary_row.text_transform */
}

#iwrgxmosvm .gt_grand_summary_row {
  color: #000000;
  background-color: #FFFFFF;
  /* grand_summary_row.background.color */
  padding: 8px;
  /* grand_summary_row.padding */
  text-transform: inherit;
  /* grand_summary_row.text_transform */
}

#iwrgxmosvm .gt_first_summary_row {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#iwrgxmosvm .gt_first_grand_summary_row {
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #A8A8A8;
}

#iwrgxmosvm .gt_table_body {
  border-top-style: solid;
  /* table_body.border.top.style */
  border-top-width: 2px;
  /* table_body.border.top.width */
  border-top-color: #A8A8A8;
  /* table_body.border.top.color */
  border-bottom-style: solid;
  /* table_body.border.bottom.style */
  border-bottom-width: 2px;
  /* table_body.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* table_body.border.bottom.color */
}

#iwrgxmosvm .gt_footnotes {
  border-top-style: solid;
  /* footnotes.border.top.style */
  border-top-width: 2px;
  /* footnotes.border.top.width */
  border-top-color: #A8A8A8;
  /* footnotes.border.top.color */
}

#iwrgxmosvm .gt_footnote {
  font-size: 90%;
  /* footnote.font.size */
  margin: 0px;
  padding: 4px;
  /* footnote.padding */
}

#iwrgxmosvm .gt_sourcenotes {
  border-top-style: solid;
  /* sourcenotes.border.top.style */
  border-top-width: 2px;
  /* sourcenotes.border.top.width */
  border-top-color: #A8A8A8;
  /* sourcenotes.border.top.color */
}

#iwrgxmosvm .gt_sourcenote {
  font-size: 90%;
  /* sourcenote.font.size */
  padding: 4px;
  /* sourcenote.padding */
}

#iwrgxmosvm .gt_center {
  text-align: center;
}

#iwrgxmosvm .gt_left {
  text-align: left;
}

#iwrgxmosvm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#iwrgxmosvm .gt_font_normal {
  font-weight: normal;
}

#iwrgxmosvm .gt_font_bold {
  font-weight: bold;
}

#iwrgxmosvm .gt_font_italic {
  font-style: italic;
}

#iwrgxmosvm .gt_super {
  font-size: 65%;
}

#iwrgxmosvm .gt_footnote_glyph {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="iwrgxmosvm" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <tr>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1"><strong>N = 34</strong></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>Coefficient</strong></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_glyph">1</sup></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
  </tr>
  <body class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">1=female</td>
      <td class="gt_row gt_center">2.9</td>
      <td class="gt_row gt_center">-18, 24</td>
      <td class="gt_row gt_center">0.8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">age</td>
      <td class="gt_row gt_center gt_striped">-0.44</td>
      <td class="gt_row gt_center gt_striped">-1.0, 0.13</td>
      <td class="gt_row gt_center gt_striped">0.13</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">range of motion before acupuncture</td>
      <td class="gt_row gt_center">0.67</td>
      <td class="gt_row gt_center">0.51, 0.83</td>
      <td class="gt_row gt_center"><0.001</td>
    </tr>
  </body>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_glyph">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>
<p>For example, for sex, the 95% CI is -18 to 24, meaning that women might plausibly have a range of motion anywhere from 18 degrees less than men to 24 degrees more. In short, we don’t have any strong evidence that sex has an effect on range of motion at all and we can see this reflected in the p value, p=0.8. There are 34 patients included in this model.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1"><span class="kw">summary</span>(rom_model)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = a ~ sex + age + b, data = lesson3d)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -60.135 -11.943   3.238  14.523  47.732 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 138.73363   29.50514   4.702 5.40e-05 ***
## sex           2.85241   10.25817   0.278    0.783    
## age          -0.43589    0.27770  -1.570    0.127    
## b             0.66924    0.07816   8.563 1.49e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 25.29 on 30 degrees of freedom
## Multiple R-squared:  0.7475, Adjusted R-squared:  0.7222 
## F-statistic:  29.6 on 3 and 30 DF,  p-value: 4.241e-09</code></pre>
<p>At the bottom of the <code>summary</code> readout there are a few miscellaneous tidbits:</p>
<ul>
<li><p>The “p-value” next to the “F-statistic” on the last line tells you whether, as a whole, your model, including the constant and three variables, is a statistically significant predictor.</p></li>
<li><p>The “Multiple R-squared” value (often referred to as just “r squared”) tells you how good a predictor it is on a scale from 0 to 1. We’ll discuss the meaning of r squared in more detail, but it is defined as the proportion of variation that you can explain using your model.</p></li>
</ul>
</div>
<div id="graphing-the-data" class="section level2">
<h2><span class="header-section-number">6.4</span> Graphing the data</h2>
<p>Graphing the data is done using the <code>ggplot</code> function from the <code>ggplot2</code> package. In short, the main inputs for the <code>ggplot</code> function are your dataset, the x variable and the y variable. You can then create a number of different plots using this data.</p>
<p>To create a scatterplot, the <code>geom_point</code> function is added to the <code>ggplot</code> function:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> lesson5a,</a>
<a class="sourceLine" id="cb138-2" title="2">       <span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> rt)) <span class="op">+</span></a>
<a class="sourceLine" id="cb138-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="05-week5_files/figure-html/section5j-1.png" width="672" /></p>
<p>This scatterplot from the “lesson5a.rds” data shows race time and age for every runner in the study. This is a useful way of getting a feel for the data before you start.</p>
</div>
<div id="logistic-regression" class="section level2">
<h2><span class="header-section-number">6.5</span> Logistic regression</h2>
<p>Logistic regression is used when the variable you wish to predict is binary (e.g. relapsed or not). The function to use is <code>glm</code>, with the option <code>family = "binomial"</code> to indicate that our outcome variable is binary.</p>
<p>Again, the first variable is the dependent variable (e.g. hypertension) and must be binary. The other variables are the predictor variables and can be binary or continuous: again, in some cases you can use ordinal variables but you have to be careful. The variables are entered into the <code>glm</code> function the same way as the <code>lm</code> function (dependent ~ predictor1 + predictor2 + …).</p>
<p>We’ll use the dataset “lesson4d.rds” as an example.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1">response_model &lt;-<span class="st"> </span><span class="kw">glm</span>(response <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>group, <span class="dt">data =</span> lesson4d, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</a>
<a class="sourceLine" id="cb139-2" title="2"><span class="kw">summary</span>(response_model)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = response ~ age + sex + group, family = &quot;binomial&quot;, 
##     data = lesson4d)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3760  -1.0954  -0.9119   1.2366   1.5590  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  0.967546   0.447037   2.164   0.0304 *
## age         -0.023270   0.009807  -2.373   0.0177 *
## sex         -0.180196   0.234045  -0.770   0.4413  
## group       -0.318300   0.205037  -1.552   0.1206  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 546.87  on 397  degrees of freedom
## Residual deviance: 538.18  on 394  degrees of freedom
##   (2 observations deleted due to missingness)
## AIC: 546.18
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>By default, R gives the coefficients in logits. To easily see the coefficients and 95% confidence intervals for all covariates as odds ratio, we can again use the <code>tbl_regression</code> function. In this case, we use the option <code>exponentiate = TRUE</code>, which indicates that odds ratios (not logits) should be presented. (You can also use this function to see the formatted logit results by using the <code>exponentiate = FALSE</code> option.)</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" title="1"><span class="kw">glm</span>(response <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>group, <span class="dt">data =</span> lesson4d, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb141-2" title="2"><span class="st">  </span><span class="kw">tbl_regression</span>(<span class="dt">exponentiate =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#hlleqxdave .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #000000;
  font-size: 16px;
  background-color: #FFFFFF;
  /* table.background.color */
  width: auto;
  /* table.width */
  border-top-style: solid;
  /* table.border.top.style */
  border-top-width: 2px;
  /* table.border.top.width */
  border-top-color: #A8A8A8;
  /* table.border.top.color */
  border-bottom-style: solid;
  /* table.border.bottom.style */
  border-bottom-width: 2px;
  /* table.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* table.border.bottom.color */
}

#hlleqxdave .gt_heading {
  background-color: #FFFFFF;
  /* heading.background.color */
  border-bottom-color: #FFFFFF;
}

#hlleqxdave .gt_title {
  color: #000000;
  font-size: 125%;
  /* heading.title.font.size */
  padding-top: 4px;
  /* heading.top.padding */
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hlleqxdave .gt_subtitle {
  color: #000000;
  font-size: 85%;
  /* heading.subtitle.font.size */
  padding-top: 2px;
  padding-bottom: 2px;
  /* heading.bottom.padding */
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hlleqxdave .gt_bottom_border {
  border-bottom-style: solid;
  /* heading.border.bottom.style */
  border-bottom-width: 2px;
  /* heading.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* heading.border.bottom.color */
}

#hlleqxdave .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  padding-top: 4px;
  padding-bottom: 4px;
}

#hlleqxdave .gt_col_heading {
  color: #000000;
  background-color: #FFFFFF;
  /* column_labels.background.color */
  font-size: 16px;
  /* column_labels.font.size */
  font-weight: initial;
  /* column_labels.font.weight */
  vertical-align: middle;
  padding: 10px;
  margin: 10px;
}

#hlleqxdave .gt_columns_top_border {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#hlleqxdave .gt_columns_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#hlleqxdave .gt_sep_right {
  border-right: 5px solid #FFFFFF;
}

#hlleqxdave .gt_group_heading {
  padding: 8px;
  color: #000000;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #A8A8A8;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#hlleqxdave .gt_empty_group_heading {
  padding: 0.5px;
  color: #000000;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #A8A8A8;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#hlleqxdave .gt_striped {
  background-color: #f2f2f2;
}

#hlleqxdave .gt_from_md > :first-child {
  margin-top: 0;
}

#hlleqxdave .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hlleqxdave .gt_row {
  padding: 8px;
  /* row.padding */
  margin: 10px;
  vertical-align: middle;
}

#hlleqxdave .gt_stub {
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #A8A8A8;
  padding-left: 12px;
}

#hlleqxdave .gt_summary_row {
  color: #000000;
  background-color: #FFFFFF;
  /* summary_row.background.color */
  padding: 8px;
  /* summary_row.padding */
  text-transform: inherit;
  /* summary_row.text_transform */
}

#hlleqxdave .gt_grand_summary_row {
  color: #000000;
  background-color: #FFFFFF;
  /* grand_summary_row.background.color */
  padding: 8px;
  /* grand_summary_row.padding */
  text-transform: inherit;
  /* grand_summary_row.text_transform */
}

#hlleqxdave .gt_first_summary_row {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#hlleqxdave .gt_first_grand_summary_row {
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #A8A8A8;
}

#hlleqxdave .gt_table_body {
  border-top-style: solid;
  /* table_body.border.top.style */
  border-top-width: 2px;
  /* table_body.border.top.width */
  border-top-color: #A8A8A8;
  /* table_body.border.top.color */
  border-bottom-style: solid;
  /* table_body.border.bottom.style */
  border-bottom-width: 2px;
  /* table_body.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* table_body.border.bottom.color */
}

#hlleqxdave .gt_footnotes {
  border-top-style: solid;
  /* footnotes.border.top.style */
  border-top-width: 2px;
  /* footnotes.border.top.width */
  border-top-color: #A8A8A8;
  /* footnotes.border.top.color */
}

#hlleqxdave .gt_footnote {
  font-size: 90%;
  /* footnote.font.size */
  margin: 0px;
  padding: 4px;
  /* footnote.padding */
}

#hlleqxdave .gt_sourcenotes {
  border-top-style: solid;
  /* sourcenotes.border.top.style */
  border-top-width: 2px;
  /* sourcenotes.border.top.width */
  border-top-color: #A8A8A8;
  /* sourcenotes.border.top.color */
}

#hlleqxdave .gt_sourcenote {
  font-size: 90%;
  /* sourcenote.font.size */
  padding: 4px;
  /* sourcenote.padding */
}

#hlleqxdave .gt_center {
  text-align: center;
}

#hlleqxdave .gt_left {
  text-align: left;
}

#hlleqxdave .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hlleqxdave .gt_font_normal {
  font-weight: normal;
}

#hlleqxdave .gt_font_bold {
  font-weight: bold;
}

#hlleqxdave .gt_font_italic {
  font-style: italic;
}

#hlleqxdave .gt_super {
  font-size: 65%;
}

#hlleqxdave .gt_footnote_glyph {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="hlleqxdave" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <tr>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1"><strong>N = 398</strong></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>OR</strong><sup class="gt_footnote_glyph">1</sup></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_glyph">1</sup></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
  </tr>
  <body class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">age</td>
      <td class="gt_row gt_center">0.98</td>
      <td class="gt_row gt_center">0.96, 1.00</td>
      <td class="gt_row gt_center">0.018</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">1 if woman, 0 if man</td>
      <td class="gt_row gt_center gt_striped">0.84</td>
      <td class="gt_row gt_center gt_striped">0.53, 1.32</td>
      <td class="gt_row gt_center gt_striped">0.4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">1 if b, 0 if a</td>
      <td class="gt_row gt_center">0.73</td>
      <td class="gt_row gt_center">0.49, 1.09</td>
      <td class="gt_row gt_center">0.12</td>
    </tr>
  </body>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_glyph">
            <em>1</em>
          </sup>
           
          OR = Odds Ratio, CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>
<p>The key things here are the odds ratios: you can say that the odds of response is multiplied by 0.98 for a one year increase in age; that women have an odds of response 0.84 of that for the men, though this is not statistically significant, and that response is lower in group 1, with an odds of 0.73 (you would also cite the p value and 95% CIs).</p>
<p>The problem here is that you can’t use any of these data to work out an individual patient’s chance of response. Now you can get R to do this for you using the <code>augment</code> function. For a binary outcome, you need to specify <code>type.predict = "response"</code> as an option so that you will get predicted probabilities (not log odds).</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1">lesson4d_pred &lt;-</a>
<a class="sourceLine" id="cb142-2" title="2"><span class="st">  </span><span class="kw">augment</span>(response_model,</a>
<a class="sourceLine" id="cb142-3" title="3">          <span class="dt">newdata =</span> lesson4d,</a>
<a class="sourceLine" id="cb142-4" title="4">          <span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>)</a></code></pre></div>
<p>NOTE: The “lesson4d_pred” dataset only includes 398 patients. If you look at the table above, you will see at the top that only 398 patients were included in the model. Any patients who are missing data for the outcome or any predictors will be excluded from the model, and will not be included in the predicted dataset.</p>
<p>If you want to look at calculating predictions from logistic regression in more detail, you’ll need logit (see below).</p>
<p>One thing to be careful about is categorical variables. Imagine that you had the patients age and cancer stage (1, 2, 3 or 4) and wanted to know whether they recurred. If you tried <code>glm(recurrence ~ age + stage, ...)</code>, then stage would be treated as if the increase in risk going from stage 1 to 2 was exactly the same as that going from 2 to 3 and 3 to 4. To tell R that it is a categorical variable, you need to use the <code>factor</code> function with the categorical variable:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" title="1">recurrence_model &lt;-</a>
<a class="sourceLine" id="cb143-2" title="2"><span class="st">  </span><span class="kw">glm</span>(recurrence <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span><span class="kw">factor</span>(stage), <span class="dt">data =</span> example5a, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</a>
<a class="sourceLine" id="cb143-3" title="3"></a>
<a class="sourceLine" id="cb143-4" title="4"><span class="kw">summary</span>(recurrence_model)</a></code></pre></div>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" title="1">recurrence_model <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb144-2" title="2"><span class="st">  </span><span class="kw">tbl_regression</span>(<span class="dt">exponentiate =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#kqtxbhydst .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #000000;
  font-size: 16px;
  background-color: #FFFFFF;
  /* table.background.color */
  width: auto;
  /* table.width */
  border-top-style: solid;
  /* table.border.top.style */
  border-top-width: 2px;
  /* table.border.top.width */
  border-top-color: #A8A8A8;
  /* table.border.top.color */
  border-bottom-style: solid;
  /* table.border.bottom.style */
  border-bottom-width: 2px;
  /* table.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* table.border.bottom.color */
}

#kqtxbhydst .gt_heading {
  background-color: #FFFFFF;
  /* heading.background.color */
  border-bottom-color: #FFFFFF;
}

#kqtxbhydst .gt_title {
  color: #000000;
  font-size: 125%;
  /* heading.title.font.size */
  padding-top: 4px;
  /* heading.top.padding */
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#kqtxbhydst .gt_subtitle {
  color: #000000;
  font-size: 85%;
  /* heading.subtitle.font.size */
  padding-top: 2px;
  padding-bottom: 2px;
  /* heading.bottom.padding */
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#kqtxbhydst .gt_bottom_border {
  border-bottom-style: solid;
  /* heading.border.bottom.style */
  border-bottom-width: 2px;
  /* heading.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* heading.border.bottom.color */
}

#kqtxbhydst .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  padding-top: 4px;
  padding-bottom: 4px;
}

#kqtxbhydst .gt_col_heading {
  color: #000000;
  background-color: #FFFFFF;
  /* column_labels.background.color */
  font-size: 16px;
  /* column_labels.font.size */
  font-weight: initial;
  /* column_labels.font.weight */
  vertical-align: middle;
  padding: 10px;
  margin: 10px;
}

#kqtxbhydst .gt_columns_top_border {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#kqtxbhydst .gt_columns_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#kqtxbhydst .gt_sep_right {
  border-right: 5px solid #FFFFFF;
}

#kqtxbhydst .gt_group_heading {
  padding: 8px;
  color: #000000;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #A8A8A8;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#kqtxbhydst .gt_empty_group_heading {
  padding: 0.5px;
  color: #000000;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #A8A8A8;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#kqtxbhydst .gt_striped {
  background-color: #f2f2f2;
}

#kqtxbhydst .gt_from_md > :first-child {
  margin-top: 0;
}

#kqtxbhydst .gt_from_md > :last-child {
  margin-bottom: 0;
}

#kqtxbhydst .gt_row {
  padding: 8px;
  /* row.padding */
  margin: 10px;
  vertical-align: middle;
}

#kqtxbhydst .gt_stub {
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #A8A8A8;
  padding-left: 12px;
}

#kqtxbhydst .gt_summary_row {
  color: #000000;
  background-color: #FFFFFF;
  /* summary_row.background.color */
  padding: 8px;
  /* summary_row.padding */
  text-transform: inherit;
  /* summary_row.text_transform */
}

#kqtxbhydst .gt_grand_summary_row {
  color: #000000;
  background-color: #FFFFFF;
  /* grand_summary_row.background.color */
  padding: 8px;
  /* grand_summary_row.padding */
  text-transform: inherit;
  /* grand_summary_row.text_transform */
}

#kqtxbhydst .gt_first_summary_row {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#kqtxbhydst .gt_first_grand_summary_row {
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #A8A8A8;
}

#kqtxbhydst .gt_table_body {
  border-top-style: solid;
  /* table_body.border.top.style */
  border-top-width: 2px;
  /* table_body.border.top.width */
  border-top-color: #A8A8A8;
  /* table_body.border.top.color */
  border-bottom-style: solid;
  /* table_body.border.bottom.style */
  border-bottom-width: 2px;
  /* table_body.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* table_body.border.bottom.color */
}

#kqtxbhydst .gt_footnotes {
  border-top-style: solid;
  /* footnotes.border.top.style */
  border-top-width: 2px;
  /* footnotes.border.top.width */
  border-top-color: #A8A8A8;
  /* footnotes.border.top.color */
}

#kqtxbhydst .gt_footnote {
  font-size: 90%;
  /* footnote.font.size */
  margin: 0px;
  padding: 4px;
  /* footnote.padding */
}

#kqtxbhydst .gt_sourcenotes {
  border-top-style: solid;
  /* sourcenotes.border.top.style */
  border-top-width: 2px;
  /* sourcenotes.border.top.width */
  border-top-color: #A8A8A8;
  /* sourcenotes.border.top.color */
}

#kqtxbhydst .gt_sourcenote {
  font-size: 90%;
  /* sourcenote.font.size */
  padding: 4px;
  /* sourcenote.padding */
}

#kqtxbhydst .gt_center {
  text-align: center;
}

#kqtxbhydst .gt_left {
  text-align: left;
}

#kqtxbhydst .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#kqtxbhydst .gt_font_normal {
  font-weight: normal;
}

#kqtxbhydst .gt_font_bold {
  font-weight: bold;
}

#kqtxbhydst .gt_font_italic {
  font-style: italic;
}

#kqtxbhydst .gt_super {
  font-size: 65%;
}

#kqtxbhydst .gt_footnote_glyph {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="kqtxbhydst" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <tr>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1"><strong>N = 1064</strong></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>OR</strong><sup class="gt_footnote_glyph">1</sup></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_glyph">1</sup></th>
    <th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
  </tr>
  <body class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">age</td>
      <td class="gt_row gt_center">1.04</td>
      <td class="gt_row gt_center">1.03, 1.05</td>
      <td class="gt_row gt_center"><0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">factor(stage)</td>
      <td class="gt_row gt_center gt_striped"></td>
      <td class="gt_row gt_center gt_striped"></td>
      <td class="gt_row gt_center gt_striped"></td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">1</td>
      <td class="gt_row gt_center">&mdash;</td>
      <td class="gt_row gt_center">&mdash;</td>
      <td class="gt_row gt_center"></td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">2</td>
      <td class="gt_row gt_center gt_striped">2.71</td>
      <td class="gt_row gt_center gt_striped">2.01, 3.66</td>
      <td class="gt_row gt_center gt_striped"><0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">3</td>
      <td class="gt_row gt_center">5.23</td>
      <td class="gt_row gt_center">3.16, 8.79</td>
      <td class="gt_row gt_center"><0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">4</td>
      <td class="gt_row gt_center gt_striped">5.88</td>
      <td class="gt_row gt_center gt_striped">3.34, 10.6</td>
      <td class="gt_row gt_center gt_striped"><0.001</td>
    </tr>
  </body>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_glyph">
            <em>1</em>
          </sup>
           
          OR = Odds Ratio, CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>
<p>What you can see here is that stage is broken into categories. The odds ratio is given comparing each stage to stage 1 (the reference). So the odds of recurrence is 2.71 higher for stage 2 compared to stage 1, 5.23 for stage 3 compared to stage 1 and 5.88 for stage 4 compared to stage 1.</p>
<p><strong>For keen students only!</strong></p>
<p>Here we look at our “response” model on the logit scale.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" title="1"><span class="kw">summary</span>(response_model)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = response ~ age + sex + group, family = &quot;binomial&quot;, 
##     data = lesson4d)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3760  -1.0954  -0.9119   1.2366   1.5590  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  0.967546   0.447037   2.164   0.0304 *
## age         -0.023270   0.009807  -2.373   0.0177 *
## sex         -0.180196   0.234045  -0.770   0.4413  
## group       -0.318300   0.205037  -1.552   0.1206  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 546.87  on 397  degrees of freedom
## Residual deviance: 538.18  on 394  degrees of freedom
##   (2 observations deleted due to missingness)
## AIC: 546.18
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Firstly, note that the p values are the same, what differs is the coefficients. Now if you are really smart, you’ll notice that the coefficient is the natural log of the odds ratios above. You can use the coefficients to work out an individual’s probability of response. We start with the constant, and subtract 0.0233 for each year of age and then subtract an additional 0.18 if a woman and 0.318 if in group 1. Call this number “l” for the log of the odds. The probability is e<sup>l</sup> / (1 + e<sup>l</sup>). Take a 53 year old man on regimen b (group 1): l = 0.9675 + -0.0233*53 + -0.318, gives -0.5841.</p>
<p>To convert, type <code>exp(-0.5841) / (exp(-0.5841)+1)</code> to get a probability of 35.8%.</p>
</div>
<div id="getting-the-area-under-the-curve" class="section level2">
<h2><span class="header-section-number">6.6</span> Getting the area-under-the-curve</h2>
<p>Imagine that you wanted to know how well a blood marker predicted cancer. Note that the blood marker could be continuous (e.g. ng/ml) or binary (positive or negative such as in a test for circulating tumor cells), doesn’t matter for our purposes.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" title="1"><span class="co"># The &quot;roc&quot; function comes from the &quot;pROC&quot; package</span></a>
<a class="sourceLine" id="cb147-2" title="2"><span class="kw">roc</span>(cancer <span class="op">~</span><span class="st"> </span>marker, <span class="dt">data =</span> example5b)</a></code></pre></div>
<pre><code>## 
## Call:
## roc.formula(formula = cancer ~ marker, data = example5b)
## 
## Data: marker in 1865 controls (cancer 0) &lt; 635 cases (cancer 1).
## Area under the curve: 0.8143</code></pre>
<p>So the marker has an area under the curve of 0.814. The <code>roc</code> function is particularly useful if you want to know the area-under-the-curve with and without a marker.</p>
<p>For instance, the code below could tell you how much the area-under-the-curve increases when you add a new marker to a model to predict cancer that already includes age.</p>
<p>First, get the AUC for the model with age only:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb149-1" title="1"><span class="co"># Original model with age</span></a>
<a class="sourceLine" id="cb149-2" title="2"><span class="kw">roc</span>(cancer <span class="op">~</span><span class="st"> </span>age, <span class="dt">data =</span> example5b)</a></code></pre></div>
<pre><code>## 
## Call:
## roc.formula(formula = cancer ~ age, data = example5b)
## 
## Data: age in 1865 controls (cancer 0) &lt; 635 cases (cancer 1).
## Area under the curve: 0.6354</code></pre>
<p>Now, calculate the AUC for the model with age and the marker:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" title="1"><span class="co"># Model adding marker</span></a>
<a class="sourceLine" id="cb151-2" title="2"><span class="kw">roc</span>(cancer <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>marker, <span class="dt">data =</span> example5b)</a></code></pre></div>
<pre><code>## $age
## 
## Call:
## roc.formula(formula = cancer ~ age, data = example5b)
## 
## Data: age in 1865 controls (cancer 0) &lt; 635 cases (cancer 1).
## Area under the curve: 0.6354
## 
## $marker
## 
## Call:
## roc.formula(formula = cancer ~ marker, data = example5b)
## 
## Data: marker in 1865 controls (cancer 0) &lt; 635 cases (cancer 1).
## Area under the curve: 0.8143</code></pre>
</div>
<div id="assignments-4" class="section level2">
<h2><span class="header-section-number">6.7</span> Assignments</h2>
<p>Regression is a very important part of statistics: I probably do more regressions that any other type of analysis, apart from than calculating basic summary data such as medians, means and proportions. So, I’ve given you lots of possibilities here. I’ve coded them: you really should try to do the bold ones, do those in italics if you can, and if you get to the rest, well, the more the merrier. The reason I have included all this is so I can go over it in class.</p>
<ul>
<li><p><strong>lesson5a.rds: These are data from marathon runners (again). Which of the following is associated with how fast runners complete the marathon: age, sex, training miles, weight?</strong></p></li>
<li><p><strong>lesson5b.rds: These are data on patients with a disease that predisposes them to cancer. The disease causes precancerous lesions that can be surgically removed. A group of recently removed lesions are analyzed for a specific mutation. Does how long a patient has had the disease affect the chance that a new lesion will have a mutation?</strong></p></li>
<li><p>lesson5c.rds: These are data from Canadian provinces giving population, unemployment rates and male and female life expectancy. Which of these variables are associated?</p></li>
<li><p><em>lesson5d.rds: These are data from mice inoculated with tumor cells and then treated with different doses of a drug. The growth rate of each animal’s tumor is then calculated. Is this drug effective?</em></p></li>
<li><p>lesson5e.rds: These are data from a study of the use of complementary medicine (e.g. massage) by UK breast cancer patients. There are data for the women’s age, time since diagnosis, presence of distant metastases, use of complementary medicine before diagnosis, whether they received a qualification after high school, the age they left education, whether usual employment is a manual trade, socioeconomic status. What predicts use of complementary medicine by women with breast cancer?</p></li>
<li><p><em>lesson5f.rds: These are the distance records for Frisbee for various ages in males. What is the relationship between age and how far a man can throw a Frisbee?</em></p></li>
<li><p><strong>lesson5g.rds: You’ve seen this data set before. Patients with lung cancer are randomized to receive either chemotherapy regime a or b and assessed for tumor response. We know there is no statistically significant difference between regimens (you can test this if you like). However, do the treatments work differently depending on sex? Do they work differently by age?</strong></p></li>
<li><p><strong>lesson5h.rds: PSA is used to screen for prostate cancer. In this data set, the researchers are looking at various forms of PSA (e.g. “nicked” PSA). What variables should be used to try to predict cancer? How accurate would this test be? (NOTE: these data were taken from a real data set, but I played around with them a bit, so please don’t draw any conclusions about PSA testing from this assignment).</strong></p></li>
<li><p>lesson5i.rds: This is a randomized trial of behavioral therapy in cancer patients with depressed mood (note that higher score means better mood). Patients are randomized to no treatment (group 1), informal contact with a volunteer (group 2) or behavior therapy with a trained therapist (group 3). What would you conclude about the effectiveness of these treatments?</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-4.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-6.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"download": "pdf"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
